import os

env = WengoGetEnvironment()

nsis_defines = {}
WengoPhoneBuildId = WengoGetVariable('WengoPhoneBuildId')
nsis_defines['PRODUCT_VERSION'] = str(WengoPhoneBuildId['buildId'])
nsis_defines['BUILD_DIR'] = env.WengoGetRootBuildDir()
nsis_defines['PRODUCT_NAME'] = 'WengoPhoneNG'
nsis_defines['QTDIR'] = os.environ['QTDIR']

if WengoDebugMode():
	compilation_mode = 'dbg-'
	nsis_defines['DEBUG'] = ''
else:
	compilation_mode = ''

installer_tag = WengoGetConsoleArgument('installer-tag')
if installer_tag != '' and installer_tag != None:
	installer_name = nsis_defines['PRODUCT_NAME'] + '-setup-' + compilation_mode + nsis_defines['PRODUCT_VERSION'] + '-%s.exe' % installer_tag
else:
	installer_name = nsis_defines['PRODUCT_NAME'] + '-setup-' + compilation_mode + nsis_defines['PRODUCT_VERSION'] + '.exe'
nsis_defines['INSTALLER_NAME'] = installer_name

env['NSISDEFINES'] = nsis_defines

nsis_inst = env.Installer('installer')

env.Alias('qtwengophone-nsis-installer', nsis_inst)
