env = WengoGetEnvironment()

qtwengophone_source_translations = [
	'qtwengophone_fr.ts',
	'qtwengophone_en.ts',
]

if WengoGetConsoleArgument('update-qtwengophone-translations'):
	env.WengoCopyToBuildDir('..\lang\\', 'wengophone\src\presentation\qt\lang')
	env.WengoQtUpdateTranslations(qtwengophone_source_translations)

qtwengophone_translations = [
	env.WengoQtLanguageRelease('qtwengophone_fr.ts', 'qtwengophone_fr.qm'),
	env.WengoQtLanguageRelease('qtwengophone_en.ts', 'qtwengophone_en.qm'),
	env.WengoQtLanguageRelease('qtwengophone_de.ts', 'qtwengophone_de.qm'),
	env.WengoQtLanguageRelease('qtwengophone_it.ts', 'qtwengophone_it.qm'),
	env.WengoQtLanguageRelease('qtwengophone_pl.ts', 'qtwengophone_pl.qm'),
	env.WengoQtLanguageRelease('qtwengophone_sv.ts', 'qtwengophone_sv.qm'),
	env.WengoQtLanguageRelease('qtwengophone_zh.ts', 'qtwengophone_zh.qm'),
	env.WengoQtLanguageRelease('qtwengophone_es.ts', 'qtwengophone_es.qm'),
	env.WengoQtLanguageRelease('qtwengophone_tr.ts', 'qtwengophone_tr.qm'),
	env.WengoQtLanguageRelease('qtwengophone_ja.ts', 'qtwengophone_ja.qm'),
]

env.WengoAlias('qtwengophone-translations', qtwengophone_translations)
