env = WengoGetEnvironment()

include_path = ['.']
sources = [
	'add.c',
	'code.c',
	'debug.c',
	'decode.c',
	'gsm_create.c',
	'gsm_decode.c',
	'gsm_destroy.c',
	'gsm_encode.c',
	'gsm_explode.c',
	'gsm_implode.c',
	'gsm_option.c',
	'gsm_print.c',
	'long_term.c',
	'lpc.c',
	'preprocess.c',
	'rpe.c',
	'short_term.c',
	'table.c'
]

env.WengoAddIncludePath(include_path)

env.WengoStaticLibrary('gsm', sources)
