env = WengoGetEnvironment()

libs = [
	'shlibloader',
	'wengoutil',
]
lib_path = []
include_path = ['include']
headers = []
sources = [
	'src/Wenbox.cpp'
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()
env.WengoStaticLibrary('wenbox', sources)

env.SConscript('src/null/SConscript')
if WengoCCMSVC():
	env.SConscript('src/yealink/SConscript')
