env = WengoGetEnvironment()

libs = []
lib_path = []
include_path = [
	'include'
]
headers = []
sources = [
	'src/fake.c',
]

if WengoCCMSVC():
	include_path += ['include/cutil/msvc']
	sources += [
		'src/msvc/dirent.c',
	]

env.WengoAddLibPath(lib_path)
env.WengoAddIncludePath(include_path)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owcutil', sources)
