env = WengoGetEnvironment()

libs = []
lib_path = []
include_path = [
	'include'
]

headers = ['include/cutil/safe-strings.h']
sources = [
	'src/fake.c',
	'src/strlcat.c',  
	'src/strlcpy.c',
]

if WengoCCMSVC():
	include_path += ['include/cutil/msvc']
	sources += [
		'src/msvc/dirent.c',
	]

env.WengoAddLibPath(lib_path)
env.WengoAddIncludePath(include_path)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owcutil', sources)
