import os, ConfigParser, shutil

env = WengoGetEnvironment()

defines = {}

sources = []

libs = [
	'gmodule-2.0',
	'glib-2.0',
	'gthread-2.0',
]

lib_path = []

include_path = [
	'src/libgaim',
	'include',
]

libs_file = []


if WengoCCMinGW():
	#get external dependencies and uncompress include files

	include_path += [
		'include/gaim/win32',
		]

	if WengoGetConsoleArgument('prepare-for-mingw'):
		if not os.path.exists(os.path.join(WengoGetSourcePath(), 'mingw',
										   'mingw.properties'))	and\
		not os.path.exists(os.path.join(WengoGetSourcePath(), './mingw')):
				os.mkdir(os.path.join(WengoGetSourcePath(), 'mingw'))
		info_file = open(os.path.join(WengoGetSourcePath(), 'mingw', 'mingw.properties'), 'w')
		info_file.write('[include_paths]\n')
		external_packages_list = [
			('ftp://ftp.mozilla.org/pub/mozilla.org/security/nss/releases/NSS_3_9_RTM/WIN954.0_OPT.OBJ/nss-3.9.zip',
			 '.+\.h'),
			('ftp://ftp.mozilla.org/pub/mozilla.org/nspr/releases/v4.4.1/WIN954.0_OPT.OBJ/nspr-4.4.1.zip',
			 '.+\.h'),
			#TODO: tarball seems to be corrupted, needs to notice tarball creator before commenting out the following line
			('http://wengofiles.wengo.fr/gtk-dev-2.6.10-rev-a.tar.gz', 'gtk_2_0/include'),
			]
		i = 0
		for (external_package, pattern_to_extract) in external_packages_list:
			for tmp_include_path in env.WengoGetExternalPackage(external_package,
															pattern_to_extract):
				info_file.write(str(i) + '=' + tmp_include_path + '\n')
				i += 1
		info_file.close()

		shutil.copyfile(os.path.join(WengoGetSourcePath(), 'src/config.h.mingw'), os.path.join(WengoGetSourcePath(), 'src/config.h'))


if os.path.exists(os.path.join(WengoGetSourcePath(), 'mingw/mingw.properties')):
	config = ConfigParser.ConfigParser()
	config.readfp(open(os.path.join(WengoGetSourcePath(), 'mingw/mingw.properties')))
	for (index, tmp_include_path) in config.items('include_paths'):
		include_path.append(tmp_include_path)

if WengoOSWindows() and WengoCCMSVC():
	lib_path += [
		'binary-lib/msvc',
	]

	libs_file += [
		'binary-lib/msvc/gaim.lib',
		'binary-lib/msvc/libgaim.dll',
		'binary-lib/msvc/iconv.dll',
		'binary-lib/msvc/intl.dll',
		'binary-lib/msvc/nspr4.dll',
		'binary-lib/msvc/nss3.dll',
		'binary-lib/msvc/nssckbi.dll',
		'binary-lib/msvc/plc4.dll',
		'binary-lib/msvc/plds4.dll',
		'binary-lib/msvc/softokn3.dll',
		'binary-lib/msvc/ssl3.dll',
		'binary-lib/msvc/zlib1.dll',
		'binary-lib/msvc/libxml2.dll',
	]

	env.WengoCopyToBuildDir('binary-lib/msvc/')
	env.WengoAddLibPath(lib_path)
	env.WengoAddIncludePath(include_path)
	env.WengoUseLibraries(libs)
	env.WengoDeclareLibrary('gaim', libs_file)

if WengoOSMacOSX():
	include_path += [
		'/sw/include', # for gnutls
	]

	lib_path += [
		'/sw/lib', # for gnutls. FIXME: works only with fink
	]

	defines['MSG_NOSIGNAL'] = 0

if WengoCCGCC() or WengoCCMinGW():

	sources += [
		'src/libgaim/account.c',
		'src/libgaim/accountopt.c',
		'src/libgaim/blist.c',
		'src/libgaim/buddyicon.c',
		'src/libgaim/cipher.c',
		'src/libgaim/circbuffer.c',
		'src/libgaim/cmds.c',
		'src/libgaim/connection.c',
		'src/libgaim/conversation.c',
		'src/libgaim/core.c',
		'src/libgaim/debug.c',
		'src/libgaim/desktopitem.c',
		'src/libgaim/dnsquery.c',
		'src/libgaim/dnssrv.c',
		'src/libgaim/eventloop.c',
		'src/libgaim/ft.c',
		'src/libgaim/getopt.c',
		'src/libgaim/getopt1.c',
		'src/libgaim/idle.c',
		'src/libgaim/imgstore.c',
		'src/libgaim/log.c',
		'src/libgaim/mime.c',
		'src/libgaim/network.c',
		'src/libgaim/notify.c',
		'src/libgaim/ntlm.c',
		'src/libgaim/plugin.c',
		'src/libgaim/pluginpref.c',
		'src/libgaim/pounce.c',
		'src/libgaim/prefix.c',
		'src/libgaim/prefs.c',
		'src/libgaim/privacy.c',
		'src/libgaim/proxy.c',
		'src/libgaim/prpl.c',
		'src/libgaim/request.c',
		'src/libgaim/roomlist.c',
		'src/libgaim/savedstatuses.c',
		'src/libgaim/server.c',
		'src/libgaim/signals.c',
		'src/libgaim/sound.c',
		'src/libgaim/sslconn.c',
		'src/libgaim/status.c',
		'src/libgaim/stringref.c',
		'src/libgaim/stun.c',
		'src/libgaim/upnp.c',
		'src/libgaim/util.c',
		'src/libgaim/value.c',
		'src/libgaim/whiteboard.c',
		'src/libgaim/xmlnode.c',
		'src/libgaim/plugins/ssl/ssl.c',
		'src/libgaim/protocols/jabber/auth.c',
		'src/libgaim/protocols/jabber/buddy.c',
		'src/libgaim/protocols/jabber/chat.c',
		'src/libgaim/protocols/jabber/disco.c',
		'src/libgaim/protocols/jabber/iq.c',
		'src/libgaim/protocols/jabber/jabber.c',
		'src/libgaim/protocols/jabber/jutil.c',
		'src/libgaim/protocols/jabber/message.c',
		'src/libgaim/protocols/jabber/oob.c',
		'src/libgaim/protocols/jabber/parser.c',
		'src/libgaim/protocols/jabber/presence.c',
		'src/libgaim/protocols/jabber/roster.c',
		'src/libgaim/protocols/jabber/si.c',
		'src/libgaim/protocols/jabber/xdata.c',
		'src/libgaim/protocols/msn/cmdproc.c',
		'src/libgaim/protocols/msn/command.c',
		'src/libgaim/protocols/msn/dialog.c',
		'src/libgaim/protocols/msn/directconn.c',
		'src/libgaim/protocols/msn/error.c',
		'src/libgaim/protocols/msn/group.c',
		'src/libgaim/protocols/msn/history.c',
		'src/libgaim/protocols/msn/httpconn.c',
		'src/libgaim/protocols/msn/msg.c',
		'src/libgaim/protocols/msn/msn.c',
		'src/libgaim/protocols/msn/nexus.c',
		'src/libgaim/protocols/msn/notification.c',
		'src/libgaim/protocols/msn/object.c',
		'src/libgaim/protocols/msn/page.c',
		'src/libgaim/protocols/msn/servconn.c',
		'src/libgaim/protocols/msn/session.c',
		'src/libgaim/protocols/msn/slp.c',
		'src/libgaim/protocols/msn/slpcall.c',
		'src/libgaim/protocols/msn/slplink.c',
		'src/libgaim/protocols/msn/slpmsg.c',
		'src/libgaim/protocols/msn/slpsession.c',
		'src/libgaim/protocols/msn/state.c',
		'src/libgaim/protocols/msn/switchboard.c',
		'src/libgaim/protocols/msn/sync.c',
		'src/libgaim/protocols/msn/table.c',
		'src/libgaim/protocols/msn/transaction.c',
		'src/libgaim/protocols/msn/user.c',
		'src/libgaim/protocols/msn/userlist.c',
		'src/libgaim/protocols/msn/msn-utils.c',
		'src/libgaim/protocols/oscar/bstream.c',
		'src/libgaim/protocols/oscar/family_admin.c',
		'src/libgaim/protocols/oscar/family_advert.c',
		'src/libgaim/protocols/oscar/family_alert.c',
		'src/libgaim/protocols/oscar/family_auth.c',
		'src/libgaim/protocols/oscar/family_bart.c',
		'src/libgaim/protocols/oscar/family_bos.c',
		'src/libgaim/protocols/oscar/family_buddy.c',
		'src/libgaim/protocols/oscar/family_chat.c',
		'src/libgaim/protocols/oscar/family_chatnav.c',
		'src/libgaim/protocols/oscar/family_feedbag.c',
		'src/libgaim/protocols/oscar/family_icbm.c',
		'src/libgaim/protocols/oscar/family_icq.c',
		'src/libgaim/protocols/oscar/family_invite.c',
		'src/libgaim/protocols/oscar/family_locate.c',
		'src/libgaim/protocols/oscar/family_odir.c',
		'src/libgaim/protocols/oscar/family_oservice.c',
		'src/libgaim/protocols/oscar/family_popup.c',
		'src/libgaim/protocols/oscar/family_stats.c',
		'src/libgaim/protocols/oscar/family_translate.c',
		'src/libgaim/protocols/oscar/family_userlookup.c',
		'src/libgaim/protocols/oscar/flap_connection.c',
		'src/libgaim/protocols/oscar/misc.c',
		'src/libgaim/protocols/oscar/msgcookie.c',
		'src/libgaim/protocols/oscar/odc.c',
		'src/libgaim/protocols/oscar/oft.c',
		'src/libgaim/protocols/oscar/oscar.c',
		'src/libgaim/protocols/oscar/oscar_data.c',
		'src/libgaim/protocols/oscar/peer.c',
		'src/libgaim/protocols/oscar/peer_proxy.c',
		'src/libgaim/protocols/oscar/rxhandlers.c',
		'src/libgaim/protocols/oscar/snac.c',
		'src/libgaim/protocols/oscar/tlv.c',
		'src/libgaim/protocols/oscar/util.c',
		'src/libgaim/protocols/yahoo/util.c',
		'src/libgaim/protocols/yahoo/yahoo.c',
		'src/libgaim/protocols/yahoo/yahoo_auth.c',
		'src/libgaim/protocols/yahoo/yahoo_crypt.c',
		'src/libgaim/protocols/yahoo/yahoo_doodle.c',
		'src/libgaim/protocols/yahoo/yahoo_filexfer.c',
		'src/libgaim/protocols/yahoo/yahoo_friend.c',
		'src/libgaim/protocols/yahoo/yahoo_packet.c',
		'src/libgaim/protocols/yahoo/yahoo_picture.c',
		'src/libgaim/protocols/yahoo/yahoo_profile.c',
		'src/libgaim/protocols/yahoo/yahoochat.c',
		'src/libgaim/protocols/yahoo/ycht.c',
	]


	include_path += [
		'src',
		'src/libgaim',
		'src/libgaim/protocols/oscar/',
	]

	lib_path += [
		'binary-lib/msvc',
	]

	defines['HAVE_CONFIG_H'] = 1
	defines['HAVE_GLIB'] = 1
	defines['GAIM_STATIC_PRPL'] = 1
	defines['HAVE_SSL'] = 1

	if WengoCCMinGW():
		libs_file += [
			'binary-lib/msvc/iconv.dll',
			'binary-lib/msvc/intl.dll',
			'binary-lib/msvc/nspr4.dll',
			'binary-lib/msvc/nss3.dll',
			'binary-lib/msvc/nssckbi.dll',
			'binary-lib/msvc/plc4.dll',
			'binary-lib/msvc/plds4.dll',
			'binary-lib/msvc/softokn3.dll',
			'binary-lib/msvc/ssl3.dll',
			'binary-lib/msvc/zlib1.dll',
			'binary-lib/msvc/libxml2.dll',
		]

		for lib_file in libs_file:
			env.WengoCopyToBuildDir(lib_file, 'binary-lib/msvc/')
		libs += [
			'nspr4',
			'nss3',
			'intl',
			'nssckbi',
			'plc4',
			'plds4',
			'softokn3',
			'ssl3',
			'zlib1',
		]


		include_path += [
			'src/libgaim/protocols/jabber/win32',
			'src/libgaim/win32',
			'src/libgaim/protocols/jabber/win32',
		]

		sources += [
			'src/libgaim/plugins/ssl/ssl-nss.c',
			'src/libgaim/win32/libc_interface.c',
			'src/libgaim/win32/win32dep.c',
			'src/libgaim/win32/untar.c',
			'src/libgaim/protocols/jabber/win32/posix.uname.c',
		]

	else:
		defines['HAVE_GNUTLS'] = 1
		sources += [
			'src/libgaim/prefix.c',
			'src/libgaim/plugins/ssl/ssl-gnutls.c',
		]

		libs += [
			'gnutls',
		]

        if WengoOSLinux() or WengoOSMacOSX():
            libs += [ 'resolv' ]

	env.ParseConfig('pkg-config --cflags --libs gthread-2.0')
	env.ParseConfig('pkg-config --cflags --libs gmodule-2.0')
	env.ParseConfig('pkg-config --cflags --libs libxml-2.0')

	env.WengoAddDefines(defines)
	env.WengoAddLibPath(lib_path)
	env.WengoAddIncludePath(include_path)
	env.WengoUseLibraries(libs)

	env.WengoStaticLibrary('gaim', sources)
