env = WengoGetEnvironment()

include_path = ['.']
sources = [
	'dec_acelp.c',
	'dec_dtx.c',
	'dec_gain.c',
	'dec_if.c',
	'dec_lpc.c',
	'dec_main.c',
	'dec_rom.c',
	'dec_util.c',
	'enc_acelp.c',
	'enc_dtx.c',
	'enc_gain.c',
	'enc_if.c',
	'enc_lpc.c',
	'enc_main.c',
	'enc_rom.c',
	'enc_util.c',
	'if_rom.c'
]

env.WengoAddIncludePath(include_path)
env.WengoAddCCFlags(WengoGetVariable('phapi_optimization_flags'))

env.WengoStaticLibrary('amrwb', sources)
