env = WengoGetEnvironment()

libs = ['m']
lib_path = []
include_path = []
defines = {}
headers = []
sources = ['testec.c', '../spxec.c', '../spxecfft.c']

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoProgram('testec', sources)
