projects = [
	'wengoscons/libs/qt4',
	'wengoscons/libs/boost',
	'wengoscons/libs/boost-unit-test',
	'wengoscons/libs/gtk',
	'wengoscons/libs/sdl',
	'wengoscons/libs/sdl_image',
	'wengoscons/libs/glib',
	'wengoscons/libs/libgaim',
	'libs/portaudio',
	'libs/global',
	'libs/timer',
	'libs/openssl',
	'libs/samplerate',
	'libs/tinyxml',
	'libs/curl',
	'libs/util',
	'libs/imwrapper',
	'libs/shlibloader',
	'libs/sipx',
	'wifo',
	'libs/sipwrapper',
	'libs/qtutil',
	'libs/skinstyle',
	'libs/sound',
	'libs/ffmpeg',
	'libs/pixertool',
	'libs/wenbox',
	'libs/webcam',
#	'libs/libgaim',
	'wengophone',
]

SConscript(dirs = projects)
