env = WengoGetEnvironment()

libs = [
	'global',
	'gthread-2.0',
	'gaim',
	'imwrapper',
]
if WengoOSLinux():
        env.ParseConfig('pkg-config --cflags --libs glib-2.0')
lib_path = []
include_path = ['../gaim']
defines = {}
headers = []
sources = [
	'GaimIMFactory.cpp',
	'GaimIMChat.cpp',
	'GaimIMConnect.cpp',
	'GaimIMPresence.cpp',
	'GaimIMContactList.cpp',
	'GaimChatMngr.cpp',
	'GaimConnectMngr.cpp',
	'GaimPresenceMngr.cpp',
	'GaimAccountMngr.cpp',
	'GaimContactListMngr.cpp',
	'GaimEnumPresenceState.cpp',
	'GaimEnumIMProtocol.cpp'
]

env.ParseConfig('pkg-config --cflags --libs gthread-2.0')
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoStaticLibrary('gaimimwrapper', sources)
