env = WengoGetEnvironment()

libs = [
	'owthread',
	'owutil',
	'phapi',
	'sfp-plugin',
	'ortp',
	'stun',
	'httptunnel',
	'tinyxml',
	'owsound',
	'imwrapper',
	'sipwrapper',
]

defines = {}
lib_path = []
include_path = [
	'../phapi'
]
link_flags = []

if WengoOSMacOSX():
	link_flags += [
		'-framework CoreFoundation',
	]

if WengoGetConsoleArgument('enable-video'):
	defines['ENABLE_VIDEO'] = 1
	libs += [
		'pixertool'
	]

if WengoGetConsoleArgument('enable-shared-phapi'):
	defines['PHAPI_DLL'] = 1

headers = []
sources = [
	'PhApiFactory.cpp',
	'PhApiWrapper.cpp',
	'PhApiCallbacks.cpp',
	'PhApiIMChat.cpp',
	'PhApiIMConnect.cpp',
	'PhApiIMPresence.cpp',
	'PhApiCodecList.cpp',
	'PhApiSFPCallbacks.cpp',
	'PhApiSFPWrapper.cpp',
	'PhApiSFPEvent.cpp',
]

env.WengoAddIncludePath(include_path)
env.WengoAddLinkFlags(link_flags)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoStaticLibrary('phapiwrapper', sources)
