projects = [
	'cutil',
	'util',
	'thread',
	'http',
	'serialization',
	'serializer',
	'shlibloader',
	'settings',
	'system',
]

if WengoCCMSVC():
	projects.append('memorydump')

SConscript(dirs = projects)
