env = WengoGetEnvironment()

env['WIN32_INSERT_DEF'] = 1

libs = [
	'osip'
]
lib_path = []
include_path = [
	'include'
]
defines = {
	'OSIP_MT' : 1,
	'ENABLE_TRACE' : 1
}
headers = []
sources = [
	'src/eXosip.c',
	'src/eXutils.c',
	'src/jauth.c',
	'src/jcall.c',
	'src/jcallback.c',
	'src/jdialog.c',
	'src/jevents.c',
	'src/jfreinds.c',
	'src/jidentity.c',
	'src/jmsg.c',
	'src/jnotify.c',
	'src/jpipe.c',
	'src/jreg.c',
	'src/jrequest.c',
	'src/jresponse.c',
	'src/jsubscribe.c',
	'src/jsubscribers.c',
	'src/misc.c',
	'src/sdp_offans.c',
	'src/udp.c'
]

if WengoOSWindows():
	libs += ['ws2_32', 'winmm', 'iphlpapi']
	defines['WIN32'] = 1

if WengoGetConsoleArgument('enable-http-tunnel'):
	defines['USE_HTTP_TUNNEL'] = 1

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)

env.WengoStaticLibrary('eXosip', sources)
