env = WengoGetEnvironment()

include_path = ['.']
sources = [
	'anaFilter.c',
	'constants.c',
	'createCB.c',
	'doCPLC.c',
	'enhancer.c',
	'filter.c',
	'FrameClassify.c',
	'gainquant.c',
	'getCBvec.c',
	'helpfun.c',
	'hpInput.c',
	'hpOutput.c',
	'iCBConstruct.c',
	'iCBSearch.c',
	'iLBC_decode.c',
	'iLBC_encode.c',
	'LPCdecode.c',
	'LPCencode.c',
	'lsf.c',
	'packing.c',
	'StateConstructW.c',
	'StateSearchW.c',
	'syntFilter.c'
]

env.WengoAddCCFlags(WengoGetVariable('phapi_optimization_flags'))
env.WengoAddIncludePath(include_path)

env.WengoStaticLibrary('ilbc', sources)
