env = WengoGetEnvironment()

libs = [
	'wengoutil',
]
lib_path = []
include_path = [
	'include'
]
defines = {}
headers = []
sources = []

if WengoOSWindows():
	sources += [
		'src/win32/Sound.cpp',
		'src/win32/SoundMixer.cpp',
		'src/win32/SoundMixerException.cpp',
		'src/win32/Volume.cpp',
		'src/win32/SoundThread.cpp',
		'src/win32/playsound/SoundFile.cpp',
		'src/win32/playsound/PlaySoundFile.cpp'
	]
	libs += ['winmm', 'advapi32']
elif WengoOSLinux():
	sources += [
		'src/unix/Sound.cpp',
		'src/unix/SoundMixer.cpp',
		'src/unix/SoundMixerException.cpp',
		'src/unix/Volume.cpp'
	]
	libs += ['qt4']

elif WengoOSMacOSX():
	sources += [
		'src/qsound/AudioDevice.cpp',
		'src/qsound/Sound.cpp',
		'src/qsound/SoundMixer.cpp',
		'src/qsound/SoundMixerException.cpp'
	]
	libs += ['qt4']

if WengoGetConsoleArgument('enable-libsound-portaudio'):
	sources += ['src/portaudio/AudioDevice.cpp']
	libs += ['portaudio']
elif WengoOSWindows():
	sources += ['src/win32/AudioDevice.cpp']
elif WengoOSLinux():
	sources += ['src/unix/AudioDevice.cpp']
	libs += ['portaudio']

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)

env.WengoStaticLibrary('sound', sources)
