env = WengoGetEnvironment()

libs = [
	'openssl',
]
lib_path = []
include_path = [
	'include',
	'lib'
]

defines = {
	'BUILDING_LIBCURL' : 1,
	'USE_SSLEAY' : 1,
	'USE_OPENSSL' : 1,
	'CURL_DISABLE_FILE' : 1,
	'CURL_DISABLE_LDAP' : 1,
	'CURL_DISABLE_DICT' : 1,
	'CURL_DISABLE_TELNET' : 1,
	'CURL_DISABLE_FTP' : 1,
	'CURL_DISABLE_TFTP' : 1,
}
if WengoDebugMode():
	defines['CURLDEBUG'] = 1

headers = []
sources = [
	'lib/base64.c',
	'lib/connect.c',
	'lib/content_encoding.c',
	'lib/cookie.c',
#	'lib/dict.c',
	'lib/easy.c',
	'lib/escape.c',
#	'lib/file.c',
	'lib/formdata.c',
#	'lib/ftp.c',
	'lib/getenv.c',
	'lib/getinfo.c',
	'lib/gtls.c',
	'lib/hash.c',
	'lib/hostares.c',
	'lib/hostasyn.c',
	'lib/hostip.c',
	'lib/hostip4.c',
	'lib/hostip6.c',
	'lib/hostsyn.c',
	'lib/hostthre.c',
	'lib/http.c',
	'lib/http_chunks.c',
	'lib/http_digest.c',
	'lib/http_negotiate.c',
	'lib/http_ntlm.c',
	'lib/if2ip.c',
	'lib/inet_ntop.c',
	'lib/inet_pton.c',
	'lib/krb4.c',
#	'lib/ldap.c',
	'lib/llist.c',
	'lib/md5.c',
	'lib/memdebug.c',
	'lib/mprintf.c',
	'lib/multi.c',
	'lib/netrc.c',
#	'lib/nwlib.c',
	'lib/parsedate.c',
	'lib/progress.c',
	'lib/security.c',
	'lib/select.c',
	'lib/sendf.c',
	'lib/share.c',
	'lib/speedcheck.c',
	'lib/sslgen.c',
	'lib/ssluse.c',
	'lib/strequal.c',
	'lib/strerror.c',
	'lib/strtok.c',
	'lib/strtoofft.c',
#	'lib/telnet.c',
#	'lib/tftp.c',
	'lib/timeval.c',
	'lib/transfer.c',
	'lib/url.c',
	'lib/version.c',
]

if WengoOSWindows():
	libs += [
		'ws2_32',
		'winmm',
		'gdi32'
	]

elif WengoOSLinux():
	libs += [
		#'idn',
	]

elif WengoOSMacOSX():
	libs += [
		'z'
	]

	defines['CURL_STATICLIB'] = 1

env.WengoAddLibPath(lib_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoAddIncludePath(include_path)

if WengoOSMacOSX():
	env.WengoStaticLibrary('wengocurl', sources)
else:
	env.WengoSharedLibrary('wengocurl', sources)
