env = WengoGetEnvironment()

libs = [
	'phapi',
	'phapi-util',
	'sfp-plugin',
	'owcurl',
	'avcodec',
]

headers = [
]

sources = [
	'WifoPluginsConsole.cpp',
	'phCallbacks.cpp',
	'sfpCallbacks.cpp',
]

if WengoCCMSVC():
	defines = {
		'PHAPI_DLL' : 1,
		'WIN32' : 1,
	}
	env.WengoAddDefines(defines)
	env.WengoAddLinkFlags(['/ENTRY:mainCRTStartup'])
#	WengoShowWindowsConsole(True)

env.WengoUseLibraries(libs)

env.WengoProgram('WifoPluginsConsole', sources, headers)
