env = WengoGetEnvironment()

env['WIN32_INSERT_DEF'] = 1

libs = [ ]
lib_path = [ ]
include_path = [
	'include',
	'include/osipparser2',
	'src/osipparser2',
	'src/osip2'
]
defines = {
	'OSIP_MT' : 1,
	'ENABLE_TRACE' : 1
}
headers = []

osipparser_sources = [
	'src/osipparser2/osip_accept.c',
	'src/osipparser2/osip_accept_encoding.c',
	'src/osipparser2/osip_accept_language.c',
	'src/osipparser2/osip_alert_info.c',
	'src/osipparser2/osip_allow.c',
	'src/osipparser2/osip_authorization.c',
	'src/osipparser2/osip_body.c',
	'src/osipparser2/osip_call_id.c',
	'src/osipparser2/osip_call_info.c',
	'src/osipparser2/osip_contact.c',
	'src/osipparser2/osip_content_disposition.c',
	'src/osipparser2/osip_content_encoding.c',
	'src/osipparser2/osip_content_length.c',
	'src/osipparser2/osip_content_type.c',
	'src/osipparser2/osip_cseq.c',
	'src/osipparser2/osip_error_info.c',
	'src/osipparser2/osip_from.c',
	'src/osipparser2/osip_header.c',
	'src/osipparser2/osip_list.c',
	'src/osipparser2/osip_md5c.c',
	'src/osipparser2/osip_message.c',
	'src/osipparser2/osip_message_parse.c',
	'src/osipparser2/osip_message_to_str.c',
	'src/osipparser2/osip_mime_version.c',
	'src/osipparser2/osip_parser_cfg.c',
	'src/osipparser2/osip_port.c',
	'src/osipparser2/osip_proxy_authenticate.c',
	'src/osipparser2/osip_proxy_authorization.c',
	'src/osipparser2/osip_record_route.c',
	'src/osipparser2/osip_rfc3264.c',
	'src/osipparser2/osip_route.c',
	'src/osipparser2/osip_to.c',
	'src/osipparser2/osip_uri.c',
	'src/osipparser2/osip_via.c',
	'src/osipparser2/osip_www_authenticate.c',
	'src/osipparser2/sdp_accessor.c',
	'src/osipparser2/sdp_message.c',
	'src/osipparser2/osip_replaces.c'
]

osip_sources = [
	'src/osip2/fsm_misc.c',
	'src/osip2/ict.c',
	'src/osip2/ict_fsm.c',
	'src/osip2/ist.c',
	'src/osip2/ist_fsm.c',
	'src/osip2/nict.c',
	'src/osip2/nict_fsm.c',
	'src/osip2/nist.c',
	'src/osip2/nist_fsm.c',
	'src/osip2/osip.c',
	'src/osip2/osip_dialog.c',
	'src/osip2/osip_event.c',
	'src/osip2/osip_negotiation.c',
	'src/osip2/osip_time.c',
	'src/osip2/osip_transaction.c',
	'src/osip2/port_condv.c',
	'src/osip2/port_fifo.c',
	'src/osip2/port_sema.c',
	'src/osip2/port_thread.c'
]

if WengoOSWindows():
	libs += ['advapi32']
	defines['WIN32'] = 1

if WengoOSLinux():
	defines.update({
		'HAVE_PTHREAD' : 1,
		'HAVE_SEMAPHORE_H' : 1
	})

if WengoOSMacOSX():
	defines.update({
		'HAVE_PTHREAD' : 1,
		'HAVE_SYS_SEM_H' : 1
	})

env.WengoUseLibraries(libs)
env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('osip', osip_sources + osipparser_sources)
