env = WengoGetEnvironment()

include_path = ['.']
sources = [
	'interf_dec.c',
	'interf_enc.c',
	'sp_dec.c',
	'sp_enc.c' 
]

env.WengoAddIncludePath(include_path)
env.WengoAddCCFlags(WengoGetVariable('phapi_optimization_flags'))

env.WengoStaticLibrary('amrnb', sources)
