# 
# WengoPhone, a voice over Internet phone
#
# Copyright (C) 2004-2005  Wengo
# Copyright (C) 2005 David Ferlier <david.ferlier@wengo.fr>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

env = WengoEnvironment()
trayicon_env = WengoQtEnvironment(env)

trayicon_sources = ["trayicon.cpp"]

trayicon_env.WengoDeclareLibraryAuto("trayicon", "libs/trayicon")

if  env.WengoOsIsWindows():
    trayicon_sources += [ "trayicon_win.cpp" ]
    trayicon_env.WengoLibAddMultiple(["shell32", "gdi32", "user32"])

elif env.WengoOsIsLinux() or env.WengoOsIsBSD():
    trayicon_sources += [ "trayicon_x11.cpp" ]

elif env.WengoOsIsDarwin():
	trayicon_sources += [ "trayicon_mac.cpp" ]

trayicon_lib = trayicon_env.WengoStaticLibrary('trayicon', trayicon_sources)
trayicon_env.WengoAlias('trayicon', trayicon_lib)
