env = WengoGetEnvironment()

WengoPhoneBuildId = {
	'buildId': WengoGetCurrentDateTime(),
	'version': '0.13',
	'revision': WengoGetSubversionRevision(),
	'sofphoneName': 'wengo',
}

WengoSetVariable('WengoPhoneBuildId', WengoPhoneBuildId)

libs = [
	'owsettings',
	'owsystem',
	'owhttp',
	'owserialization',
	'owserializer',
	'imwrapper',
	'sipwrapper',
	'wenbox',
	'tinyxml',
	'owsound',
	'netlib',
	'qt4',
]
lib_path = []
include_path = ['.']
defines = {}
headers = []

envBuildId = WengoGetEnvironment()
if WengoGetConsoleArgument('nobuildid'):
	envBuildId.Append(
		CPPDEFINES = {
			'DD_BUILDID': '0LL',
			'DD_VERSION': '0',
			'DD_REVISION': 0,
			'DD_SOFTPHONE_NAME': 'wengo'
		}
	)
else:
	envBuildId.Append(
		CPPDEFINES = {
			'DD_BUILDID': str(WengoPhoneBuildId['buildId']) + 'LL',
			'DD_VERSION': WengoPhoneBuildId['version'],
			'DD_REVISION': WengoPhoneBuildId['revision'],
			'DD_SOFTPHONE_NAME': WengoPhoneBuildId['sofphoneName']
		}
	)

buildId = envBuildId.Object(source = 'WengoPhoneBuildId.cpp')

envBuildId.WengoStaticLibrary('buildId', buildId)

sources = [
	'model/WengoPhone.cpp',
	'model/SipCallbacks.cpp',
	'model/config/Config.cpp',
	'model/config/ConfigXMLSerializer.cpp',
	'model/config/ConfigManager.cpp',
	'model/config/ConfigManagerFileStorage.cpp',
	'model/config/LanguageList.cpp',
	'model/config/ClassicConfigImporter.cpp',
	'model/config/StartupSettingListener.cpp',
	'model/connect/Connect.cpp',
	'model/connect/ConnectHandler.cpp',
	'model/chat/ChatHandler.cpp',
	'model/wenbox/WenboxPlugin.cpp',
	'model/phonecall/SipAddress.cpp',
	'model/phonecall/PhoneCall.cpp',
	'model/phonecall/PhoneCallState.cpp',
	'model/phonecall/PhoneCallStateClosed.cpp',
	'model/phonecall/PhoneCallStateDefault.cpp',
	'model/phonecall/PhoneCallStateDialing.cpp',
	'model/phonecall/PhoneCallStateError.cpp',
	'model/phonecall/PhoneCallStateHold.cpp',
	'model/phonecall/PhoneCallStateIncoming.cpp',
	'model/phonecall/PhoneCallStateTalking.cpp',
	'model/phonecall/PhoneCallStateResumed.cpp',
	'model/phonecall/PhoneCallStateRinging.cpp',
	'model/phonecall/ConferenceCall.cpp',
	'model/phonecall/ConferenceCallParticipant.cpp',
	'model/phoneline/PhoneLine.cpp',
	'model/phoneline/PhoneLineStateDefault.cpp',
	'model/phoneline/PhoneLineStateOk.cpp',
	'model/phoneline/PhoneLineStateClosed.cpp',
	'model/phoneline/PhoneLineStateTimeout.cpp',
	'model/phoneline/PhoneLineStateServerError.cpp',
	'model/account/NetworkDiscovery.cpp',
	'model/account/wengo/WengoAccount.cpp',
	'model/account/wengo/WengoAccountRPCLayer.cpp',
	'model/account/wengo/WengoAccountXMLLayer.cpp',
	'model/account/wengo/WengoAccountParser.cpp',
#	'model/account/LocalNetworkAccount.cpp',
	'model/account/SipAccount.cpp',
	'model/presence/Presence.cpp',
	'model/presence/PresenceHandler.cpp',
	'model/presence/MyPresenceStateOnline.cpp',
	'model/presence/MyPresenceStateOffline.cpp',
	'model/presence/MyPresenceStateAway.cpp',
	'model/presence/MyPresenceStateDoNotDisturb.cpp',
	'model/presence/MyPresenceStateInvisible.cpp',
	'model/presence/MyPresenceStateForward.cpp',
	'model/contactlist/Contact.cpp',
	'model/contactlist/ContactXMLSerializer.cpp',
	'model/contactlist/ContactList.cpp',
	'model/contactlist/ContactListXMLSerializer.cpp',
	'model/contactlist/ContactGroup.cpp',
	'model/contactlist/ContactListFileStorage.cpp',
	'model/contactlist/ContactListRPCStorage.cpp',
	'model/contactlist/IMContactListHandler.cpp',
	'model/profile/ProfileXMLSerializer.cpp',
	'model/profile/UserProfile.cpp',
	'model/profile/UserProfileXMLSerializer.cpp',
	'model/profile/UserProfileFileStorage.cpp',
	'model/profile/EnumSex.cpp',
	'model/profile/StreetAddress.cpp',
	'model/profile/StreetAddressXMLSerializer.cpp',
	'model/history/History.cpp',
	'model/history/HistoryMemento.cpp',
	'model/history/HistoryMementoCollection.cpp',
	'model/webservices/WengoWebService.cpp',
	'model/webservices/sms/Sms.cpp',
	'model/webservices/info/WsInfo.cpp',
	'model/webservices/subscribe/Subscribe.cpp',
	'model/webservices/softupdate/SoftUpdate.cpp',
	'control/wenbox/CWenboxPlugin.cpp',
	'control/CWengoPhone.cpp',
	'control/connect/CConnectHandler.cpp',
	'control/chat/CChatHandler.cpp',
	'control/presence/CPresenceHandler.cpp',
	'control/phoneline/CPhoneLine.cpp',
	'control/phonecall/CPhoneCall.cpp',
	'control/contactlist/CContact.cpp',
	'control/contactlist/CContactList.cpp',
	'control/contactlist/CContactGroup.cpp',
	'control/webservices/sms/CSms.cpp',
	'control/webservices/softupdate/CSoftUpdate.cpp',
	'control/webservices/info/CWsInfo.cpp',
	'control/webservices/subscribe/CSubscribe.cpp',
	'control/history/CHistory.cpp',

	'presentation/PFactory.cpp'
]

env.WengoCopyToBuildDir('../sounds', 'sounds')
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoStaticLibrary('wengophone', sources)
