env = WengoGetEnvironment()

libs = [
	'owutil',
]
lib_path = []
include_path = ['..']
headers = []
sources = [
	'src/SharedLibLoader.cpp'
]

if WengoOSWindows():
	sources += ['src/win32/Win32SharedLibLoader.cpp']
elif WengoOSPosix():
	sources += ['src/posix/PosixSharedLibLoader.cpp']
else:
	sources += ['src/null/NullSharedLibLoader.cpp']

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)

env.WengoStaticLibrary('shlibloader', sources)

env.SConscript('tests/SConscript')
