env = WengoGetEnvironment()

libs = []
lib_path = []
include_path = [
	'include',
]
headers = []
sources = [
	'src/util.c',
	'src/comparator.c',
	'src/linkedlist.c',
	'src/mappinglist.c',
]



if WengoCCMSVC():
	include_path += ['include/phapi-util/msvc']
	sources += [
		'src/msvc/pthread.c',
		'src/msvc/unistd.c',
	]
	defines = {
		'WIN32' : 1,
	}
	env.WengoAddDefines(defines)

env.WengoAddLibPath(lib_path)
env.WengoUseLibraries(libs)
env.WengoAddIncludePath(include_path)


env.WengoStaticLibrary('phapi-util', sources)
