import os, sys

env = WengoGetEnvironment()

cc_flags = []
link_flags = []
#It does not build without -pthread on some GNU/Linux distros (e.g Debian Sarge)
if WengoOSLinux():
	cc_flags += ['-pthread']
	link_flags += ['-pthread']

BOOSTVER='1_33_1'
libs = []
if WengoCCGCC() and not WengoOSWindows():
	conf = Configure(env)
	if conf.CheckLib('boost_thread-gcc-mt'):
		libs += [
			'boost_thread-gcc-mt',
			'boost_serialization-gcc-mt',
			'boost_signals-gcc-mt',
			'boost_regex-gcc-mt',
			'boost_program_options-gcc-mt',
		]
	else:
		libs += [
			'boost_thread',
			'boost_serialization',
			'boost_signals',
			'boost_regex',
			'boost_program_options',
		]
	env = conf.Finish()
if WengoCCMSVC():
	libs += [
		'libboost_thread-vc71-mt.lib',
		'libboost_serialization-vc71-mt.lib',
		'libboost_signals-vc71-mt.lib',
		'libboost_regex-vc71-mt.lib',
		'libboost_program_options-vc71-mt.lib',
	]

if WengoCCMinGW():
	libs += [
		'libboost_thread-mgw-mt',
		'libboost_serialization-mgw-mt',
		'libboost_signals-mgw-mt',
		'libboost_regex-mgw-mt',
		'libboost_program_options-mgw-mt',
	]

lib_path = []
include_path = []
boost_lib_dir = ''
boost_inc_dir = ''

if not os.environ.has_key('BOOSTINCLUDEDIR'):
	if WengoOSMacOSX():
		boost_inc_dir = '/usr/local/include/boost-' + BOOSTVER
	if WengoOSWindows():
		boost_inc_dir  = 'C:\\Boost\\include\\boost-' + BOOSTVER
else:
	boost_inc_dir = os.environ['BOOSTINCLUDEDIR']

if not os.environ.has_key('BOOSTLIBDIR'):
	if WengoOSMacOSX():
		boost_lib_dir = '/usr/local/lib'
	if WengoOSWindows():
		boost_lib_dir = 'C:\\Boost\\lib'
else:
	boost_lib_dir = os.environ['BOOSTLIBDIR']

include_path += [boost_inc_dir]
lib_path += [boost_lib_dir]

if WengoOSMacOSX():
	libs += [
		'boost_thread',
		'boost_serialization',
		'boost_signals',
		'boost_regex',
	]

	#Installed from source code
	if os.path.exists(boost_inc_dir) and os.path.exists(boost_lib_dir):
		print "libpath :" + str(lib_path)
		print "include path :" + str(include_path)

	#Installed with Darwinports
	elif os.path.exists('/opt/local/include/') and os.path.exists('/opt/local/lib'):
		include_path += ['/opt/local/include']
		lib_path += ['/opt/local/lib']
	else:
		print 'Boost library not found'
		sys.exit(1)

if WengoOSLinux():
	if os.path.exists('/usr/local/include/boost-' + BOOSTVER):
		include_path += ['/usr/local/include/boost-' + BOOSTVER]
		lib_path += ['/usr/local/lib']
		cc_flags += ['-pthread']

defines = {}
headers = []
sources = []

env.WengoAddLibPath(lib_path)
env.WengoAddCCFlags(cc_flags)
env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoDeclareSystemLibrary('boost')
