env = WengoGetEnvironment()

libs = [
	'owutil',
	'owthread',
]
lib_path = []
include_path = ['include']
link_flags = []
headers = [
]
sources = [
	'src/LocalServer.cpp',
]

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owlocalserver', sources, headers)

