env = WengoGetEnvironment()

libs = []
lib_path = ['bin']
include_path = ['include']
headers = []
sources = []

env.WengoAddLibPath(lib_path)
env.WengoUseLibraries(libs)
env.WengoAddIncludePath(include_path)

files = []
if WengoOSWindows():
	files += [
		'bin/iconv.dll',
		'bin/intl.dll',
		'bin/libglib-2.0-0.dll',
		'bin/libgthread-2.0-0.dll',
		'bin/sipXtapi.dll',
		'bin/sipXtapi.lib',
		'bin/sipXtapid.dll',
		'bin/sipXtapid.lib',
		'bin/pcre.dll'
	]

env.WengoDeclareLibrary('sipXtapi', files)
