env = WengoGetEnvironment()

libs = [
	'global',
	'avcodec'
]
lib_path = []
defines = {}
include_path = ['include']
headers = [
	'include/pixertool.h'
]
sources = [
	'src/pixertool.cpp',
	'src/ffmpeg/ffmpeg-pixertool.c',
]

if WengoCCMSVC():
	libs += ['winmm', 'strmiids', 'comsupp']
	sources += ['src/directx/directx-pixertool.cpp']

elif WengoOSLinux():
	sources += ['src/v4l/v4l-pixertool.c']

elif WengoOSMacOSX():
	sources += ['src/quicktime/quicktime-pixertool.c']

else:
	sources += ['src/null-pixertool.cpp']

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)

env.WengoStaticLibrary('pixertool', sources, headers)

env.SConscript('tests/SConscript')
