# 
# WengoPhone, a voice over Internet phone
#
# Copyright (C) 2004-2005  Wengo
# Copyright (C) 2005 David Ferlier <david.ferlier@wengo.fr>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

env = WengoEnvironment()
zip_env = WengoQtEnvironment(env)

zip_sources = [
    "zip.cpp",
    "minizip/unzip.c"
]

zip_include_paths = [
    zip_env.WengoGetBuildDirRelativePath("libs/zip")
]

if zip_env.WengoOsIsWindows():
    zip_include_paths += [
        zip_env.WengoGetBuildDirRelativePath("libs/zip/minizip/win32")
    ]

zip_lib_paths = [
    zip_env.WengoGetBuildDirRelativePath("libs/zip")
]

zip_libs = [ "wengozip" ]

env.WengoDeclareLibrary("zip", include_paths = zip_include_paths,
        lib_paths = zip_lib_paths, libraries = zip_libs)

zip_env.WengoUseLibraryHeaders("zip")
zip_env.WengoLibAdd("libz")

zip_lib = zip_env.WengoStaticLibrary('wengozip', zip_sources)
zip_env.WengoAlias('zip', zip_lib)
