env = WengoGetEnvironment()

env['WIN32_INSERT_DEF'] = 1

libs = [
	'srtp',
	'osip',
	'ortp',
	'openssl',
]
lib_path = ['include']
include_path = ['include']
defines = {
	'_DEBUG_' : 1,
	'USE_SRTP' : 1
}
headers = [
        'include/error.h',
        'include/sdp.h',
        'include/crypto.h',
        'include/session.h',
        'include/sessionsManager.h',
        'include/svoip.h',
        'include/svoip_phapi.h',
        'include/phmedia.h',
        'include/dh.h'
]
sources = [
        'src/error.c',
        'src/sdp.c',
        'src/crypto.c',
        'src/sessionsManager.c',
        'src/svoip.c',
        'src/svoip_phapi.c',
        'src/dh.c'
]

if WengoOSWindows():
	defines['WIN32'] = 1

if WengoOSLinux() or WengoOSMacOSX():
	env.ParseConfig('pkg-config --cflags --libs gthread-2.0')

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('sVoIP', sources)
