"""
Automatic file list gen
@author Ovidiu Ciule <ovidiu.ciule@wengo.com>
"""

import os

message = """\"\"\"Automatically generated by fileListGen.py
WARNING: if you modify this file, save a copy and remove this warning!\"\"\"
"""

def print_ls(outputFile, dirname, names):
	if os.path.basename(dirname).startswith("."):
		del(names[:])
		return
	print "Dir: " + dirname + "\n"
	append_task(outputFile, dirname, names)

def append_task(outputFile, dirname, names):
	files = 0
	outputText = "tasks.append ([\"" + dirname + "\",\n"
	for name in names:
		if ((not name.startswith(".")) and (not os.path.isdir(dirname+"/"+name)) 
			and (not name.startswith("CoIpManagerBinding")) and (name.endswith(".h")) 
			and (not name.startswith("std")) and (not name.startswith("I"))):
			print "\t" + name
			outputText += "\t\"" + os.popen("find /home/ociule/coipmanager/libs -name '"
				+ os.path.splitext(name)[0] + "'.h").readlines()[0].rstrip() + "\",\n"
			files += 1;
	if (files == 0):
		return
	outputText = outputText[0:len(outputText)-2]
	outputText += "])\n"
	outputFile.write(outputText)

outputFile = open("fileListTemp.py", "w")
#outputFile.write(message)
#outputFile.write("tasks = []\n")
os.path.walk("/home/ociule/coipmanager/libs/sipwrapper/include",print_ls, outputFile)
#os.path.walk("/home/ociule/coipmanager/libs/coipmanager", print_ls, outputFile)
outputFile.close()
