env = WengoGetEnvironment()

libs = [
	'wengophone',
	'phapiwrapper',
]

headers = [
]

sources = [
	'NetworkDiscoveryTest.cpp'
]

env.WengoUseLibraries(libs)

env.WengoProgram('networkdiscovery-test', sources, headers)
