env = WengoGetEnvironment()

libs = [
	'owutil',
	'sipwrapper',
	'sipXtapi',
]
lib_path = []
include_path = []
defines = {}
headers = []
sources = [
	'SipXWrapper.cpp',
	'SipXCallbacks.cpp'
]

env.WengoUseLibraries(libs)
env.WengoStaticLibrary('sipxwrapper', sources)
