env = WengoGetEnvironment()

env['WIN32_INSERT_DEF'] = 1

libs = []
lib_path = []
include_path = [
	'include',
	'src'
]
defines = {
	'RTP_MAX_SIZE' : 8192
}
headers = []
sources = [
	'src/avprofile.c',
	'src/ortp.c',
	'src/ortpdlkm.c', 
	'src/payloadtype.c',
	'src/port_fct.c',
	'src/posixtimer.c',
	'src/rtpmod.c',
	'src/rtpparse.c',
	'src/rtpsession.c',
	'src/rtpsignaltable.c',
	'src/rtptimer.c',
	'src/scheduler.c',
	'src/sessionset.c',
	'src/str_utils.c',
	'src/export.c',
	'src/telephonyevents.c',
	'src/rtcp.c'
]


if WengoGetConsoleArgument('enable-http-tunnel'):
	defines['USE_HTTP_TUNNEL'] = 1

if WengoOSWindows():
	defines['WIN32'] = 1
	libs += ['ws2_32', 'winmm']

if WengoOSLinux() or WengoOSMacOSX():
	env.ParseConfig('pkg-config --cflags --libs gthread-2.0')

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('ortp', sources)
