#!/usr/bin/env ruby

# simple script to generate simple cmake modules for finding libraries (packages)
# Alexander Neundorf <neundorf@kde.org>, 2006
# usage: generate_findpackage_file
# then you will be prompted to enter the required parameters

print("Name of package: ")
package=gets.chomp

print("\npkgconfig package name (e.g. \"libxml-2.0\", leave empty to skip pkgconfig): ")
pkgconfig=gets.chomp

print("\nLook for header (e.g. \"jpeglib.h\" or \"libxml/xpath.h\"): ")
header=gets.chomp

print("\nLook for header subdir (e.g. \"libxml2\", empty to skip ): ")
incSubDir=gets.chomp

print("\nLook for library (e.g. \"xml2\" or \"avcodec avutil\"): ")
libs=gets.chomp

cmakeIncDirName=package.upcase+"_INCLUDE_DIR"
cmakeIncDirNames=package.upcase+"_INCLUDE_DIRS"
cmakeLibNames=package.upcase+"_LIBRARIES"
cmakeDefsName=package.upcase+"_DEFINITIONS"
cmakeFoundName=package.upcase+"_FOUND"
cmakeQuietName=package+"_FIND_QUIETLY"
cmakeRequiredName=package+"_FIND_REQUIRED"

file=File.new("Find#{package}.cmake", "w+")


file.printf("# - Try to find #{package}\n")
file.printf("# Once done this will define\n")
file.printf("#\n")
file.printf("#  #{cmakeFoundName} - system has #{package}\n")
file.printf("#  #{cmakeIncDirNames} - the #{package} include directory\n")
file.printf("#  #{cmakeLibNames} - Link these to use #{package}\n")
file.printf("#  #{cmakeDefsName} - Compiler switches required for using #{package}\n")
file.printf("#\n")

file.printf("\n")
file.printf("\n")

file.printf("if (#{cmakeLibNames} AND #{cmakeIncDirNames})\n")
file.printf("  # in cache already\n")
file.printf("  set(#{cmakeFoundName} TRUE)\n")
file.printf("else (#{cmakeLibNames} AND #{cmakeIncDirNames})\n")

if not pkgconfig.empty?
   file.printf("  # use pkg-config to get the directories and then use these values\n")
   file.printf("  # in the FIND_PATH() and FIND_LIBRARY() calls\n")
   file.printf("  include(UsePkgConfig)\n\n")
   file.printf("  pkgconfig(#{pkgconfig} _#{package}IncDir _#{package}LinkDir _#{package}LinkFlags _#{package}Cflags)\n\n")
   file.printf("  set(#{cmakeDefsName} ${_#{package}Cflags})\n\n")
end


file.printf("  find_path(#{cmakeIncDirName}\n")
file.printf("    NAMES\n")
file.printf("      #{header}\n")
file.printf("    PATHS\n")
if not pkgconfig.empty?
   file.printf("      ${_#{package}IncDir}\n")
end
file.printf("      /usr/include\n")
file.printf("      /usr/local/include\n")

if not incSubDir.empty?
   file.printf("    PATH_SUFFIXES\n")
	file.printf("      #{incSubDir}\n")
end
file.printf("  )\n")

file.printf("\n")

libs.split(" ").each do |lib|
	file.printf("  find_library(#{lib.upcase}_LIBRARY\n")
	file.printf("    NAMES\n")
	file.printf("      #{lib}\n")
	file.printf("    PATHS\n")
	if not pkgconfig.empty?
		file.printf("      ${_#{package}LinkDir}\n")
	end
	file.printf("      /usr/lib\n")
	file.printf("      /usr/local/lib\n")
	file.printf("  )\n")
end

file.printf("\n")

file.printf("  set(#{cmakeIncDirNames}\n")
file.printf("    ${#{cmakeIncDirName}}\n")
file.printf("  )\n")
file.printf("  set(#{cmakeLibNames}\n")
libs.split(" ").each do |lib|
	file.printf("    ${#{lib.upcase}_LIBRARY}\n")
end
file.printf(")\n")

file.printf("\n")

file.printf("  if (#{cmakeIncDirNames} AND #{cmakeLibNames})\n")
file.printf("     set(#{cmakeFoundName} TRUE)\n")
file.printf("  endif (#{cmakeIncDirNames} AND #{cmakeLibNames})\n\n")

file.printf("  if (#{cmakeFoundName})\n")
file.printf("    if (NOT #{cmakeQuietName})\n")
file.printf("      message(STATUS \"Found #{package}: ${#{cmakeLibNames}}\")\n")
file.printf("    endif (NOT #{cmakeQuietName})\n")
file.printf("  else (#{cmakeFoundName})\n")
file.printf("    if (#{cmakeRequiredName})\n")
file.printf("      message(FATAL_ERROR \"Could not find #{package}\")\n")
file.printf("    endif (#{cmakeRequiredName})\n")
file.printf("  endif (#{cmakeFoundName})\n\n")


file.printf("  # show the #{cmakeIncDirNames} and #{cmakeLibNames} variables only in the advanced view\n")
file.printf("  mark_as_advanced(#{cmakeIncDirNames} #{cmakeLibNames})\n\n")

file.printf("endif (#{cmakeLibNames} AND #{cmakeIncDirNames})\n\n")

printf("Done, generated Find#{package}.cmake\n")
