env = WengoGetEnvironment()

libs = [
	'owutil',
]
lib_path = []
include_path = ['include']
link_flags = []
headers = []
sources = [
	'src/Timer.cpp',
	'src/Thread.cpp',
]

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owthread', sources)

env.SConscript('tests/SConscript')
