env = WengoGetEnvironment()

libs = [
	'wengoutil',
]

include_path = ['include']

headers = [
	'include/imwrapper/EnumIMProtocol.h',
	'include/imwrapper/EnumPresenceState.h',
	'include/imwrapper/IMAccount.h',
	'include/imwrapper/IMAccountHandler.h',
	'include/imwrapper/IMChat.h',
	'include/imwrapper/IMChatSession.h',
	'include/imwrapper/IMChatMap.h',
	'include/imwrapper/IMConnect.h',
	'include/imwrapper/IMPresence.h',
	'include/imwrapper/IMWrapperFactory.h',
]

sources = [
	'src/IMAccountHandler.cpp',
	'src/IMChatMap.cpp',
	'src/IMChatSession.cpp',
	'src/IMContact.cpp',
	'src/IMWrapperFactory.cpp',
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)

env.WengoStaticLibrary('imwrapper', sources, headers)

env.SConscript('src/gaim/SConscript')
env.SConscript('tests/SConscript')
