env = WengoGetEnvironment()

libs = [
	'owsettings',
	'glib-2.0',
	'tinyxml',
]

if WengoOSMacOSX():
	env.ParseConfig('pkg-config --cflags --libs glib-2.0')

include_path = ['include']

headers = [
	'include/imwrapper/EnumIMProtocol.h',
	'include/imwrapper/EnumPresenceState.h',
	'include/imwrapper/IMAccount.h',
	'include/imwrapper/IMAccountXMLSerializer.h',
	'include/imwrapper/IMAccountParameters.h',
	'include/imwrapper/IMAccountParametersXMLSerializer.h',
	'include/imwrapper/IMAccountHandler.h',
	'include/imwrapper/IMAccountHandlerXMLSerializer.h',
	'include/imwrapper/IMAccountHandlerStorage.h',
	'include/imwrapper/IMAccountHandlerFileStorage.h',
	'include/imwrapper/IMChat.h',
	'include/imwrapper/IMChatSession.h',
	'include/imwrapper/IMConnect.h',
	'include/imwrapper/IMContact.h',
	'include/imwrapper/IMContactXMLSerializer.h',
	'include/imwrapper/IMContactList.h',
	'include/imwrapper/IMContactSet.h',
	'include/imwrapper/IMPresence.h',
	'include/imwrapper/IMWrapperFactory.h',
]

sources = [
	'src/IMAccount.cpp',
	'src/IMAccountXMLSerializer.cpp',
	'src/IMAccountParameters.cpp',
	'src/IMAccountParametersXMLSerializer.cpp',
	'src/IMAccountHandler.cpp',
	'src/IMAccountHandlerXMLSerializer.cpp',
	'src/IMAccountHandlerFileStorage.cpp',
	'src/IMChatSession.cpp',
	'src/IMContact.cpp',
	'src/IMContactXMLSerializer.cpp',
	'src/IMContactSet.cpp',
	'src/IMWrapperFactory.cpp',
	'src/EnumIMProtocol.cpp',
	'src/EnumPresenceState.cpp',
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)

env.WengoStaticLibrary('imwrapper', sources, headers)

env.SConscript('tests/SConscript')
