env = WengoGetQt4Environment()

libs = [
	'qt4',
	'owutil',
	'boost-unit-test',
	'libboost_unit_test_framework-vc71-mt.lib'
]
lib_path = []
include_path = []
headers = []
sources = [
	'EventTest.cpp',
]

env.WengoUseLibraries(libs)

env.WengoProgram('util-tests', sources)
