env = WengoGetQt4Environment()

libs = [
	'qtutil',
	'qt4',
	'xpcomwengophone',
]
lib_path = []
include_path = []
export_defines = {}
defines = {}
link_flags = []
headers = []
sources = [
	'main.cpp',
	'MainWindow.cpp',
]

env.WengoCopyToBuildDir('.')
env.WengoAddDefines(defines)
env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoProgram('testxpcomwengophone', sources, headers)
