env = WengoGetQt4Environment()

libs = [
	'qtutil',
	'qt4',
	'xpcomwengophone',
]
lib_path = []
include_path = []
export_defines = {}
defines = {}
link_flags = []
if WengoOSMacOSX():
	link_flags += ['-framework AudioUnit', '-framework AudioToolbox', '-framework CoreAudio']
headers = []
sources = [
	'main.cpp',
	'MainWindow.cpp',
]

env.WengoCopyToBuildDir('MainWindow.ui', '.')
env.WengoAddDefines(defines)
env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoProgram('testxpcomwengophone', sources, headers)
