env = WengoGetEnvironment()

libs = [
	'glib-2.0',
	'gthread-2.0',
]
lib_path = ['bin']
include_path = ['include']
headers = []
sources = []

env.WengoAddLibPath(lib_path)
env.WengoUseLibraries(libs)
env.WengoAddIncludePath(include_path)

files = []
if WengoOSWindows():
	files += [
		#needed by gaim
		#'bin/iconv.dll',
		#'bin/intl.dll',
		'bin/sipXtapi.dll',
		'bin/sipXtapi.lib',
		'bin/sipXtapid.dll',
		'bin/sipXtapid.lib',
		'bin/pcre.dll'
	]

env.WengoDeclareLibrary('sipXtapi', files)
