
env = WengoEnvironment()
gsm_env = env.Copy()

gsm_sources = [
    "add.c",
    "code.c",
    "debug.c",
    "decode.c",
	"gsm_create.c",
    "gsm_decode.c",
    "gsm_destroy.c",
	"gsm_encode.c",
    "gsm_explode.c",
    "gsm_implode.c",
	"gsm_option.c",
    "gsm_print.c",
    "long_term.c",
	"lpc.c",
    "preprocess.c",
    "rpe.c",
    "short_term.c",
	"table.c"
]

gsm_decl = gsm_env.WengoDeclareLibraryAuto("gsm", "wifo/exosip/phapi/gsm")
gsm_lib = gsm_env.WengoStaticLibrary("gsm", gsm_sources)
gsm_env.WengoAlias("gsm", gsm_lib)
