env = WengoGetEnvironment()

libs = [
	'owcurl',
	'owthread',
]
lib_path = []
include_path = ['include']
link_flags = []
headers = []
sources = [
	'src/HttpRequest.cpp',
	'src/NullHttpRequest.cpp',
	'src/CurlHttpRequest.cpp',
]

if WengoOSWindows():
	libs += ['advapi32', 'shell32']

elif WengoOSMacOSX():
	link_flags += ['-framework CoreFoundation']

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owhttp', sources)

env.SConscript('tests/SConscript')
