env = WengoGetEnvironment()

link_flags = []

libs = [
	'wengophone',
	'phapiwrapper',
	'gaimimwrapper',
]

headers = [
]

sources = [
	'WengoPhoneIMWrapperTest.cpp',
	'main.cpp',
]

if WengoOSMacOSX():
       link_flags += [ 
                '-framework CoreAudio',
                '-framework AudioToolbox',
                '-framework AudioUnit',
		'-framework CoreServices'
        ]

env.WengoUseLibraries(libs)
env.WengoAddLinkFlags(link_flags)
env.WengoProgram('wengophoneimwrapper-test', sources, headers)
