env = WengoGetEnvironment()

libs = [
	'wengoutil',
]

include_path = [
	'include',
]

projects = [
	'src/sipx',
	'src/phapi',
	'src/null',
]

headers = [
	'include/sipwrapper/EnumPhoneCallState.h',
	'include/sipwrapper/EnumPhoneLineState.h',
	'include/sipwrapper/SipWrapper.h',
	'include/sipwrapper/SipWrapperFactory.h'
	'include/sipwrapper/WebcamVideoFrame.h',
]

sources = [
	'src/SipWrapperFactory.cpp',
]

env.WengoUseLibraries(libs)
env.WengoAddIncludePath(include_path)
env.WengoStaticLibrary('sipwrapper', sources, headers)

env.WengoAddDoxyfile()
env.SConscript(dirs = projects)

#env.SConscript('tests/SConscript')
