env = WengoGetEnvironment()

libs = [
	'owserialization',
	'tinyxml',
	'owthread',
]
lib_path = []
include_path = ['include']
link_flags = []
headers = []
sources = [
	'src/Settings.cpp',
	'src/AutomaticSettings.cpp',
	'src/StringListXMLSerializer.cpp',
	'src/SettingsXMLSerializer.cpp',
]

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owsettings', sources)

env.SConscript('tests/SConscript')
