env = WengoGetEnvironment()

libs = [
	'owutil'
]
lib_path = []
include_path = ['include']
link_flags = []
headers = []
sources = ['src/fake.cpp']

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owserialization', sources)

env.SConscript('tests/SConscript')
