env = WengoGetEnvironment()

libs = []
lib_path = ['../binary-lib']
include_path = [
	'..'
]
defines = {}
headers = []
sources = [
	'integer.c',
	'mathematics.c',
	'intfloat_readwrite.c',
	'rational.c'
]

env.WengoAddIncludePath(include_path)
env.WengoAddLibPath(lib_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)

#if WengoOSLinux():
	#env.WengoStaticLibrary('libavutil', sources)

files = []
#if WengoOSWindows():
#	files += [
#		'../binary-lib/avcodec.dll',
#		'../binary-lib/avcodec.lib'
#	]

env.WengoDeclareLibrary('avutil', files)
