env = WengoGetEnvironment()

if WengoOSMacOSX():
	include_path = [
		'include'
	]
	
	env.WengoAddIncludePath(include_path)
	env.WengoAutoconf('speex', ['libspeex/.libs/libspeex.dylib', 'libspeex/.libs/libspeex.1.dylib'])

else:
	env.SConscript('libspeex/SConscript')
