#define ARCH_X86 1
#define HAVE_MMX 1
#define __CPU__ 586
#define TUNECPU generic
#define HAVE_BUILTIN_VECTOR 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LRINTF 1
#define HAVE_VHOOK 1
#define CONFIG_HAVE_DLOPEN 1
#define CONFIG_HAVE_DLFCN 1
#define CONFIG_NETWORK 1
#define CONFIG_DECODERS 1
#define CONFIG_ENCODERS 1
#define CONFIG_ZLIB 1
#define CONFIG_NETWORK 1
#define HAVE_MALLOC_H 1
#define SIMPLE_IDCT 1
#define restrict __restrict__
#define CONFIG_H263_ENCODER 1
#define CONFIG_H263P_ENCODER 1
#define CONFIG_MPEG4_ENCODER 1
#define CONFIG_AUDIO_OSS 1
