env = WengoGetEnvironment()

libs = [
	'owutil',
]
lib_path = []
include_path = ['include']
link_flags = []
headers = []
sources = [
	'src/Startup.cpp',
	'src/WebBrowser.cpp',
]

if WengoOSWindows():
	libs += ['advapi32', 'shell32']

elif WengoOSMacOSX():
	link_flags += ['-framework CoreFoundation']

if WengoCCMSVC():
	libs += ['shlwapi']

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owsystem', sources)

env.SConscript('tests/SConscript')
