env = WengoGetEnvironment()

libs = ['owutil']
lib_path = []
include_path = ['include']
headers = []
sources = [
	'src/Startup.cpp',
    'src/Processes.cpp',
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()
env.WengoStaticLibrary('owsystem', sources)
