env = WengoGetEnvironment()

libs = [
	'owutil',
	'sipwrapper',
]
lib_path = []
include_path = [
	'../null',
]
defines = {}
headers = []
sources = [
	'NullSipWrapper.cpp'
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoStaticLibrary('nullsipwrapper', sources)
