env = WengoGetEnvironment()

libs = [
	'portaudio',
	'samplerate'
]

headers = [
]

sources = [
	'main.c'
]

link_flags = [
	'-framework CoreAudio'
]

env.WengoAddLinkFlags(link_flags)
env.WengoUseLibraries(libs)
env.WengoProgram('portaudio-test', sources, headers)
env.Depends('portaudio-test', ['sine16bit.sw'])

