env = WengoGetEnvironment()

libs = []
include_path = [
	'include'
]
headers = ['include/wtimer.h']
sources = ['src/timer_impl.c']
defines = {}

if WengoOSWindows():
	sources += ['src/win32_mm/impl_timer.c']
	defines['TIMER_ENABLE_WINMM_IMPL'] = 1

else:
	sources += ['src/clock_gettime/impl_timer.c']
	defines['TIMER_ENABLE_CLOCK_GETTIME_IMPL'] = 1

	if WengoOSLinux():
		libs += ['rt', 'pthread']

env.WengoAddDefines(defines)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)

env.WengoStaticLibrary('wtimer', sources, headers)
