env = WengoGetEnvironment()

libs = [
	'imwrapper',
	'owutil'
]
lib_path = []
include_path = ['../null']
defines = {}
headers = []
sources = [
	'NullIMFactory.cpp',
	'NullIMChat.cpp',
	'NullIMConnect.cpp',
	'NullIMPresence.cpp',
	'NullIMContactList.cpp',
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoStaticLibrary('nullimwrapper', sources)
