# 
# WengoPhone, a voice over Internet phone
#
# Copyright (C) 2004-2005  Wengo
# Copyright (C) 2005 David Ferlier <david.ferlier@wengo.fr>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

env = WengoEnvironment()
iconset_env = WengoQtEnvironment(env)

iconset_decl = env.WengoDeclareLibraryAuto("iconset", "libs/iconset")
iconset_decl.AddSubIncludePath("psipng")

iconset_sources = ["iconset.cpp", "anim.cpp"]

iconset_env.WengoUseLibrary("zip")
iconset_env.WengoUseLibraryHeaders("iconset")

iconset_lib = iconset_env.WengoStaticLibrary("iconset", iconset_sources)
iconset_env.WengoAlias("iconset", iconset_lib)

test_env = WengoQtEnvironment(env)
test_src = ["test/main.cpp"]
test_env.WengoUseLibrary("iconset")
test_env.WengoUseLibrary("zip")
test_pgr = test_env.WengoProgram("iconset_test", test_src)
iconset_env.WengoAlias("iconset_test", test_pgr)




