env = WengoGetEnvironment()

libs = []
lib_path = []
include_path = ['.', 'include']
defines = {}
headers = []
sources = [
  'src/fidlib.c',
]

if WengoOSWindows():
  defines['T_MSVC'] = 1

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('fidlib', sources)
