env = WengoGetEnvironment()

libs = [
	'boost',
	'owcutil',
]

lib_path = []

include_path = ['..']

link_flags = []

headers = []

sources = [
	'src/exception/Exception.cpp',
	'src/Base64.cpp',
	'src/CountryList.cpp',
	'src/Date.cpp',
	'src/File.cpp',
	'src/Logger.cpp',
	'src/Path.cpp',
	'src/NonCopyable.cpp',
	'src/OWPicture.cpp',
	'src/String.cpp',
	'src/StringList.cpp',
	'src/Time.cpp',
	'src/Uuid.cpp',
	'src/WebBrowser.cpp',
]

if WengoOSWindows():
	libs += ['advapi32', 'shell32', 'Rpcrt4']

	sources += [
		'src/win/UuidWin.cpp',
	]

elif WengoOSMacOSX():
	frameworks = [
		'CoreFoundation',
	]

	env.WengoAddFrameworks(frameworks)

	sources += [
		'src/mac/UuidMac.cpp',
	]

elif WengoOSLinux() or WengoOSBSD():
	libs += ['uuid']
	sources += ['src/unix/UuidUnix.cpp']

if WengoCCMSVC():
	libs += ['shlwapi']

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owutil', sources)

env.SConscript('tests/SConscript')
