env = WengoGetEnvironment()

libs = [
	'boost',
	'owcutil',
]
lib_path = []
include_path = ['include']
link_flags = []
headers = []
sources = [
	'src/exception/Exception.cpp',
	'src/Path.cpp',
	'src/Startup.cpp',
	'src/WebBrowser.cpp',
	'src/Date.cpp',
	'src/Time.cpp',
	'src/StringList.cpp',
	'src/String.cpp',
	'src/File.cpp',
	'src/Base64.cpp',
	'src/Logger.cpp',
	'src/IdGenerator.cpp',
	'src/Picture.cpp',
]

if WengoOSWindows():
	libs += ['advapi32', 'shell32', 'Rpcrt4']
	sources += ['src/win/Uuid.cpp']
else:
	sources += ['src/unix/Uuid.cpp']

if WengoOSLinux():
	libs += ['uuid']

elif WengoOSMacOSX():
	link_flags += ['-framework CoreFoundation']

if WengoCCMSVC():
	libs += ['shlwapi']

env.WengoAddLinkFlags(link_flags)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owutil', sources)

env.SConscript('tests/SConscript')
