env = WengoGetEnvironment()

projects = [
	'src',
	'src/model/sipwrapper/sipx',
	'src/model/sipwrapper/phapi',
	'src/model/sipwrapper/null',
	'src/model/imwrapper/null',
	'src/presentation/gtk',
	'src/presentation/qt',
	'src/presentation/xpcom',
	'src/presentation/xpcom/tests'
]

env.WengoAddDoxyfile()
env.SConscript(dirs = projects)

env.SConscript('tests/SConscript')
