env = WengoGetQt4Environment()

sources = ['main.cpp', 'FtpUpload.cpp', 'QtCrashReport.cpp']
headers = ['FtpUpload.h', 'QtCrashReport.h']
libs = ['owthread', 'owcutil', 'owcurl', 'owutil', 'qt4', 'boost', 'qtutil']

forms = [
    'CrashReport.ui',
]

for form in forms:
    header = env.WengoCompileQt4UiFile(form)
    headers += [ header ]


env.WengoUseLibraries(libs)
env.WengoProgram('crashreport', sources, headers)
