/**
 * WengoPhone, a voice over Internet phone
 * Copyright (C) 2004-2006  Wengo
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef COUNTRIES_H
#define COUNTRIES_H

/** A Country is the association of its ISO 3166-1 code + its english name. */
struct Country {

	/** English country name. */
	std::string englishName;

	/** ISO 3166-1 code. */
	std::string iso3166Code;
};

/** Number of countries available. */
static const int COUNTRIES_SIZE = 250;

/**
 * Country list from ISO 3166-1.
 *
 * This list states the country names (official short names in English) in
 * alphabetical order as given in ISO 3166-1 and the corresponding ISO
 * 3166-1-alpha-2 code elements. The list is updated whenever a change to the
 * official code list in ISO 3166-1 is effected by the ISO 3166/MA. It lists 240
 * official short names and code elements. One line of text contains one entry.
 *
 * @see http://www.iso.org/iso/en/prods-services/iso3166ma/02iso-3166-code-lists/index.html
 * @author Tanguy Krotoff
 */
static const Country COUNTRIES[COUNTRIES_SIZE] = {
	{ "AFGHANISTAN", "AF" },
	{ "ÅLAND ISLANDS", "AX" },
	{ "ALBANIA", "AL" },
	{ "ALGERIA", "DZ" },
	{ "AMERICAN SAMOA", "AS" },
	{ "ANDORRA", "AD" },
	{ "ANGOLA", "AO" },
	{ "ANGUILLA", "AI" },
	{ "ANTARCTICA", "AQ" },
	{ "ANTIGUA AND BARBUDA", "AG" },
	{ "ARGENTINA", "AR" },
	{ "ARMENIA", "AM" },
	{ "ARUBA", "AW" },
	{ "AUSTRALIA", "AU" },
	{ "AUSTRIA", "AT" },
	{ "AZERBAIJAN", "AZ" },
	{ "BAHAMAS", "BS" },
	{ "BAHRAIN", "BH" },
	{ "BANGLADESH", "BD" },
	{ "BARBADOS", "BB" },
	{ "BELARUS", "BY" },
	{ "BELGIUM", "BE" },
	{ "BELIZE", "BZ" },
	{ "BENIN", "BJ" },
	{ "BERMUDA", "BM" },
	{ "BHUTAN", "BT" },
	{ "BOLIVIA", "BO" },
	{ "BOSNIA AND HERZEGOVINA", "BA" },
	{ "BOTSWANA", "BW" },
	{ "BOUVET ISLAND", "BV" },
	{ "BRAZIL", "BR" },
	{ "BRITISH INDIAN OCEAN TERRITORY", "IO" },
	{ "BRUNEI DARUSSALAM", "BN" },
	{ "BULGARIA", "BG" },
	{ "BURKINA FASO", "BF" },
	{ "BURUNDI", "BI" },
	{ "CAMBODIA", "KH" },
	{ "CAMEROON", "CM" },
	{ "CANADA", "CA" },
	{ "CAPE VERDE", "CV" },
	{ "CAYMAN ISLANDS", "KY" },
	{ "CENTRAL AFRICAN REPUBLIC", "CF" },
	{ "CHAD", "TD" },
	{ "CHILE", "CL" },
	{ "CHINA", "CN" },
	{ "CHRISTMAS ISLAND", "CX" },
	{ "COCOS (KEELING) ISLANDS", "CC" },
	{ "COLOMBIA", "CO" },
	{ "COMOROS", "KM" },
	{ "CONGO", "CG" },
	{ "CONGO, THE DEMOCRATIC REPUBLIC OF THE", "CD" },
	{ "COOK ISLANDS", "CK" },
	{ "COSTA RICA", "CR" },
	{ "COTE D'IVOIRE", "CI" },
	{ "CROATIA", "HR" },
	{ "CUBA", "CU" },
	{ "CYPRUS", "CY" },
	{ "CZECH REPUBLIC", "CZ" },
	{ "DENMARK", "DK" },
	{ "DJIBOUTI", "DJ" },
	{ "DOMINICA", "DM" },
	{ "DOMINICAN REPUBLIC", "DO" },
	{ "ECUADOR", "EC" },
	{ "EGYPT", "EG" },
	{ "EL SALVADOR", "SV" },
	{ "EQUATORIAL GUINEA", "GQ" },
	{ "ERITREA", "ER" },
	{ "ESTONIA", "EE" },
	{ "ETHIOPIA", "ET" },
	{ "FALKLAND ISLANDS (MALVINAS)", "FK" },
	{ "FAROE ISLANDS", "FO" },
	{ "FIJI", "FJ" },
	{ "FINLAND", "FI" },
	{ "FRANCE", "FR" },
	{ "FRENCH GUIANA", "GF" },
	{ "FRENCH POLYNESIA", "PF" },
	{ "FRENCH SOUTHERN TERRITORIES", "TF" },
	{ "GABON", "GA" },
	{ "GAMBIA", "GM" },
	{ "GEORGIA", "GE" },
	{ "GERMANY", "DE" },
	{ "GHANA", "GH" },
	{ "GIBRALTAR", "GI" },
	{ "GREECE", "GR" },
	{ "GREENLAND", "GL" },
	{ "GRENADA", "GD" },
	{ "GUADELOUPE", "GP" },
	{ "GUAM", "GU" },
	{ "GUATEMALA", "GT" },
	{ "GUERNSEY", " GG" },
	{ "GUINEA", "GN" },
	{ "GUINEA-BISSAU", "GW" },
	{ "GUYANA", "GY" },
	{ "HAITI", "HT" },
	{ "HEARD ISLAND AND MCDONALD ISLANDS", "HM" },
	{ "HOLY SEE (VATICAN CITY STATE)", "VA" },
	{ "HONDURAS", "HN" },
	{ "HONG KONG", "HK" },
	{ "HUNGARY", "HU" },
	{ "ICELAND", "IS" },
	{ "INDIA", "IN" },
	{ "INDONESIA", "ID" },
	{ "IRAN, ISLAMIC REPUBLIC OF", "IR" },
	{ "IRAQ", "IQ" },
	{ "IRELAND", "IE" },
	{ "ISLE OF MAN", "IM" },
	{ "ISRAEL", "IL" },
	{ "ITALY", "IT" },
	{ "JAMAICA", "JM" },
	{ "JAPAN", "JP" },
	{ "JERSEY", "JE" },
	{ "JORDAN", "JO" },
	{ "KAZAKHSTAN", "KZ" },
	{ "KENYA", "KE" },
	{ "KIRIBATI", "KI" },
	{ "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KP" },
	{ "KOREA, REPUBLIC OF", "KR" },
	{ "KUWAIT", "KW" },
	{ "KYRGYZSTAN", "KG" },
	{ "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LA" },
	{ "LATVIA", "LV" },
	{ "LEBANON", "LB" },
	{ "LESOTHO", "LS" },
	{ "LIBERIA", "LR" },
	{ "LIBYAN ARAB JAMAHIRIYA", "LY" },
	{ "LIECHTENSTEIN", "LI" },
	{ "LITHUANIA", "LT" },
	{ "LUXEMBOURG", "LU" },
	{ "MACAO", "MO" },
	{ "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "MK" },
	{ "MADAGASCAR", "MG" },
	{ "MALAWI", "MW" },
	{ "MALAYSIA", "MY" },
	{ "MALDIVES", "MV" },
	{ "MALI", "ML" },
	{ "MALTA", "MT" },
	{ "MARSHALL ISLANDS", "MH" },
	{ "MARTINIQUE", "MQ" },
	{ "MAURITANIA", "MR" },
	{ "MAURITIUS", "MU" },
	{ "MAYOTTE", "YT" },
	{ "MEXICO", "MX" },
	{ "MICRONESIA, FEDERATED STATES OF", "FM" },
	{ "MOLDOVA, REPUBLIC OF", "MD" },
	{ "MONACO", "MC" },
	{ "MONGOLIA", "MN" },
	{ "MONTSERRAT", "MS" },
	{ "MOROCCO", "MA" },
	{ "MOZAMBIQUE", "MZ" },
	{ "MYANMAR", "MM" },
	{ "NAMIBIA", "NA" },
	{ "NAURU", "NR" },
	{ "NEPAL", "NP" },
	{ "NETHERLANDS", "NL" },
	{ "NETHERLANDS ANTILLES", "AN" },
	{ "NEW CALEDONIA", "NC" },
	{ "NEW ZEALAND", "NZ" },
	{ "NICARAGUA", "NI" },
	{ "NIGER", "NE" },
	{ "NIGERIA", "NG" },
	{ "NIUE", "NU" },
	{ "NORFOLK ISLAND", "NF" },
	{ "NORTHERN MARIANA ISLANDS", "MP" },
	{ "NORWAY", "NO" },
	{ "OMAN", "OM" },
	{ "PAKISTAN", "PK" },
	{ "PALAU", "PW" },
	{ "PALESTINIAN TERRITORY, OCCUPIED", "PS" },
	{ "PANAMA", "PA" },
	{ "PAPUA NEW GUINEA", "PG" },
	{ "PARAGUAY", "PY" },
	{ "PERU", "PE" },
	{ "PHILIPPINES", "PH" },
	{ "PITCAIRN", "PN" },
	{ "POLAND", "PL" },
	{ "PORTUGAL", "PT" },
	{ "PUERTO RICO", "PR" },
	{ "QATAR", "QA" },
	{ "REUNION", "RE" },
	{ "ROMANIA", "RO" },
	{ "RUSSIAN FEDERATION", "RU" },
	{ "RWANDA", "RW" },
	{ "SAINT HELENA", "SH" },
	{ "SAINT KITTS AND NEVIS", "KN" },
	{ "SAINT LUCIA", "LC" },
	{ "SAINT PIERRE AND MIQUELON", "PM" },
	{ "SAINT VINCENT AND THE GRENADINES", "VC" },
	{ "SAMOA", "WS" },
	{ "SAN MARINO", "SM" },
	{ "SAO TOME AND PRINCIPE", "ST" },
	{ "SAUDI ARABIA", "SA" },
	{ "SENEGAL", "SN" },
	{ "SERBIA AND MONTENEGRO", "CS" },
	{ "SEYCHELLES", "SC" },
	{ "SIERRA LEONE", "SL" },
	{ "SINGAPORE", "SG" },
	{ "SLOVAKIA", "SK" },
	{ "SLOVENIA", "SI" },
	{ "SOLOMON ISLANDS", "SB" },
	{ "SOMALIA", "SO" },
	{ "SOUTH AFRICA", "ZA" },
	{ "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "GS" },
	{ "SPAIN", "ES" },
	{ "SRI LANKA", "LK" },
	{ "SUDAN", "SD" },
	{ "SURINAME", "SR" },
	{ "SVALBARD AND JAN MAYEN", "SJ" },
	{ "SWAZILAND", "SZ" },
	{ "SWEDEN", "SE" },
	{ "SWITZERLAND", "CH" },
	{ "SYRIAN ARAB REPUBLIC", "SY" },
	{ "TAIWAN, PROVINCE OF CHINA", "TW" },
	{ "TAJIKISTAN", "TJ" },
	{ "TANZANIA, UNITED REPUBLIC OF", "TZ" },
	{ "THAILAND", "TH" },
	{ "TIMOR-LESTE", "TL" },
	{ "TOGO", "TG" },
	{ "TOKELAU", "TK" },
	{ "TONGA", "TO" },
	{ "TRINIDAD AND TOBAGO", "TT" },
	{ "TUNISIA", "TN" },
	{ "TURKEY", "TR" },
	{ "TURKMENISTAN", "TM" },
	{ "TURKS AND CAICOS ISLANDS", "TC" },
	{ "TUVALU", "TV" },
	{ "UGANDA", "UG" },
	{ "UKRAINE", "UA" },
	{ "UNITED ARAB EMIRATES", "AE" },
	{ "UNITED KINGDOM", "GB" },
	{ "UNITED STATES", "US" },
	{ "UNITED STATES MINOR OUTLYING ISLANDS", "UM" },
	{ "URUGUAY", "UY" },
	{ "UZBEKISTAN", "UZ" },
	{ "VANUATU", "VU" },
	{ "VENEZUELA", "VE" },
	{ "VIET NAM", "VN" },
	{ "VIRGIN ISLANDS, BRITISH", "VG" },
	{ "VIRGIN ISLANDS, U.S.", "VI" },
	{ "WALLIS AND FUTUNA", "WF" },
	{ "WESTERN SAHARA", "EH" },
	{ "YEMEN", "YE" },
	{ "ZAMBIA", "ZM" },
	{ "ZIMBABWE", "ZW" }
};

#endif	//COUNTRIES_H
