import os

env = WengoGetEnvironment()

libs = []
lib_path = []
include_path = []
lib_files = []

if WengoOSWindows():
	if WengoCCMSVC():
		include_path += [
			'include',
		]

		lib_path += [
			'binary-lib/msvc',
		]

		lib_files += [	
			'binary-lib/msvc/glib-2.0.lib',
			'binary-lib/msvc/libglib-2.0-0.dll',
		]

		env.WengoAddLibPath(lib_path)
		env.WengoAddIncludePath(include_path)
		env.WengoUseLibraries(libs)
		env.WengoDeclareLibrary('glib-2.0', lib_files)

else:
	env.ParseConfig('pkg-config --cflags --libs glib-2.0')
