# 
# WengoPhone, a voice over Internet phone
#
# Copyright (C) 2004-2005  Wengo
# Copyright (C) 2005 David Ferlier <david.ferlier@wengo.fr>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

env = WengoEnvironment()
buildid_env = env.Copy()

TMPL_BUILDID = "static const Q_ULLONG BUILDID = %s;\n"
TMPL_BUILDIDSTRING = "static const char *BUILDID_STRING = \"%s\"; \n"

if "gcc" in env.WengoGetTools():
    TMPL_BUILDID = "static const Q_ULLONG BUILDID = %sULL;\n"

def generate_build_id(env, target, source):
    out = open(target[0].path, 'a+')
    out.write(TMPL_BUILDID % source[0].get_contents())
    out.write(TMPL_BUILDIDSTRING % source[1].get_contents())
    out.close()

buildid_target = buildid_env.Command('buildid.h', [
	Value(env.WengoGetVariable("WENGOPHONE_ID")),
	Value(env.WengoGetVariable("WENGOPHONE_ID_STRING")),
	], generate_build_id)

buildid_env.WengoAlias("softphone-buildid", buildid_target)
