# 
# WengoPhone, a voice over Internet phone
#
# Copyright (C) 2004-2005  Wengo
# Copyright (C) 2005 David Ferlier <david.ferlier@wengo.fr>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# Author David Ferlier <david.ferlier@wengo.fr>
#
# Note: all these scripts contain compilation techniques that were
# obtained by looking at the ffmpeg's configure.in
#
# It works for our usage but will possibly break for something else
# than what we do : h263 basic encoding
#

import SCons.Util

env = WengoEnvironment()

ffmpeg_env = env.Copy()
if ffmpeg_env.WengoOsIsWindows():
    ffmpeg_env.Tool("mingw")
    ffmpeg_env["SHLIBPREFIX"] = ""
    ffmpeg_env["SHLIBSUFFIX"] = ".dll"
    ffmpeg_env["LIBSUFFIX"] = ".lib"
    ffmpeg_env["LIBPREFIX"] = ""

ffmpeg_env.WengoCacheEnvironment("ffmpeg")
ffmpeg_env['SHCCFLAGS'] = SCons.Util.CLVar('$CCFLAGS')
ffmpeg_env.WengoCCFlagsAdd("-O3")

ffmpeg_env.WengoCppDefineRemove("DEBUG")
ffmpeg_env.WengoCppDefineAdd("HAVE_AV_CONFIG_H")
ffmpeg_env.WengoCppDefineAdd("_GNU_SOURCE")
ffmpeg_env.WengoCppDefineAdd("_LARGEFILE_SOURCE")
ffmpeg_env.WengoCppDefineSet("_FILE_OFFSET_BITS", 64)

ffmpeg_env.WengoCCFlagsAdd("-Wno-switch")

ffmpeg_env.WengoBuildInDir("SConfigHGeneration", "libs/ffmpeg")
ffmpeg_env.WengoBuildInDir("binary-lib/SConscript", "libs/ffmpeg/binary-lib")
ffmpeg_env.WengoBuildInDir("libavutil/SConscript", "libs/ffmpeg/libavutil")
ffmpeg_env.WengoBuildInDir("libavcodec/SConscript", "libs/ffmpeg/libavcodec")
