# 
# WengoPhone, a voice over Internet phone
#
# Copyright (C) 2004-2005  Wengo
# Copyright (C) 2005 David Ferlier <david.ferlier@wengo.fr>
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

env = WengoEnvironment()
video_env = WengoQtEnvironment(env)

video_sources = []

video_libdec = env.WengoDeclareLibraryAuto("video", "libs/video")

video_env.WengoCppDefineAdd("WEBCAM_DLLEXPORTS")

if video_env.WengoOsIsLinux():
    video_sources += ["webcam/WebcamDevice_linux.cpp"]
elif video_env.WengoOsIsWindows():
    video_sources += ["webcam/WebcamDevice_windx.cpp"]
else:
    video_sources += ["webcam/WebcamDevice_null.cpp"]

video_lib = video_env.Library('video', video_sources)
video_env.WengoAlias('video', video_lib)
