env = WengoGetEnvironment()

libs = [
	'wengophone',
	'boost-unit-test',
]

include_path = [
	'.'
]

headers = [
	'ContactListTest.h'
]

sources = [
	'main.cpp'
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)

env.WengoProgram('wengophone-test', sources, headers)

env.SConscript('networkdiscovery-test/SConscript')
env.SConscript('wengophoneimwrapper-test/SConscript')
env.SConscript('GaimTest/SConscript')
