libs = []
lib_path = [
	'../binary-lib',
	'.'
]
include_path = [
	'..',
	'../libavutil',
	'.'
]
defines = {}
headers = []

i386_sources =  [
	'i386/fdct_mmx.c',
	'i386/cputest.c',
	'i386/dsputil_mmx.c',
	'i386/mpegvideo_mmx.c',
	'i386/idct_mmx.c',
	'i386/motion_est_mmx.c',
	'i386/simple_idct_mmx.c',
	'i386/vp3dsp_mmx.c',
	'i386/vp3dsp_sse2.c',
]

i386_sse_sources = [
	'i386/fft_sse.c',
]

core_sources = [
	'bitstream.c',
	'utils.c',
	'mem.c',
	'allcodecs.c',
	'mpegvideo.c',
	'jrevdct.c',
	'jfdctfst.c',
	'jfdctint.c',
	'mpegaudio.c',
	'ac3enc.c',
	'mjpeg.c',
	'resample.c',
	'resample2.c',
	'dsputil.c',
	'motion_est.c',
	'imgconvert.c',
	'imgresample.c',
	'mpeg12.c',
	'mpegaudiodec.c',
	'pcm.c',
	'simple_idct.c',
	'ratecontrol.c',
	'adpcm.c',
	'eval.c',
	'error_resilience.c',
	'fft.c',
	'mdct.c',
	'raw.c',
	'golomb.c',
	'cabac.c',
	'dpcm.c',
	'adx.c',
	'faandct.c',
	'parser.c',
	'g726.c',
	'vp3dsp.c',
	'h264idct.c',
	'rangecoder.c',
	'pnm.c',
	'h263.c',
	'msmpeg4.c',
	'h263dec.c',
	'dvdsub.c',
	'dvbsub.c',
	'dvbsubdec.c'
]

sources = core_sources + i386_sources

env = WengoGetEnvironment()

env.WengoAddIncludePath(include_path)
env.WengoAddLibPath(lib_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)

sse_env = env.Copy()
sse_env.WengoAddCCFlags(['-msse'])
#sse_lib = sse_env.SharedObject('fft_sse', i386_sse_sources)

#if WengoOSWindows():
#	env.WengoSharedLibrary('libavcodec', sources + sse_lib)

files = []
if WengoOSWindows():
	copycmd = "copy"
	files += [
		'../binary-lib/avcodec.dll',
	]

slib = env.File('../binary-lib/avcodec.lib')
dlib = env.File('avcodec.lib')

cmd = env.Command(dlib, slib, copycmd + " $SOURCES > $TARGET")
env.WengoDeclareLibrary('avcodec', files + [cmd])
