option(WITH_PORTAUDIO_DSOUND "Build PortAudio with DirectSound support" OFF)
option(WITH_VIDEO "Build phApi with video support" ON)
option(WITH_BUILDID "Build WengoPhone with buildId (builds faster without)" OFF)
option(WITH_SAMPLERATE "Build phApi with samplerate support" OFF)
option(WITH_PHAPI_AUDIO_ALSA "Build phApi with alsa support" ON)
option(WITH_PHAPI_AUDIO_ARTS "Build phApi with arts support" OFF)
option(WITH_PHAPI_AUDIO_ESD "Build phApi with esd support" OFF)
option(WITH_HTTPTUNNEL "Build phApi with httptunnel support" ON)
option(WITH_QOS_DEBUG "Build phApi with QOS debug support" OFF)
option(WITH_EMBEDDED_PHAPI "Build phApi with embedded target support" OFF)
option(WITH_SPEEXWB_REPLACES_AMRWB "Build phApi with Speex-WB/AMR-WB hack" OFF)
option(WITH_SPEEXWB_REPLACES_AMRNB "Build phApi with Speex-WB/AMR-NB hack" OFF)
option(WITH_SPEEXWB_REPLACES_G726WB "Build phApi with Speex-WB/G726-WB hack" ON)
