option(PORTAUDIO_INTERNAL "Use internal PortAudio" ON)
option(FFMPEG_INTERNAL "Use internal FFmpeg" OFF)
option(SPEEX_INTERNAL "Use internal Speex" ON)

# Not yet implemented
#option(SAMPLERATE_INTERNAL "Use internal Samplerate" ON)

option(WENGOPHONE_RESOURCEDIR_PATH "WengoPhone: use ${DATA_INSTALL_DIR} as hardcoded resource path" ON)
option(WENGOPHONE_XV_SUPPORT "Build WengoPhone with XV hardware acceleration support" ON)
option(PORTAUDIO_DIRECTSOUND_SUPPORT "Build PortAudio with DirectSound support" OFF)
option(PHAPI_VIDEO_SUPPORT "Build phApi with video support" ON)
option(BUILDID_SUPPORT "Build WengoPhone/phApi with buildId (builds faster without)" OFF)
option(PHAPI_SAMPLERATE_SUPPORT "Build phApi with Samplerate support" OFF)
option(PHAPI_AUDIO_ALSA_SUPPORT "Build phApi with ASLA support" ON)
option(PHAPI_AUDIO_ARTS_SUPPORT "Build phApi with aRts support" OFF)
option(PHAPI_AUDIO_ESD_SUPPORT "Build phApi with ESD support" OFF)
option(PHAPI_HTTPTUNNEL_SUPPORT "Build phApi with httptunnel support" ON)
option(PHAPI_QOS_DEBUG_SUPPORT "Build phApi with QOS debug support" OFF)
option(PHAPI_EMBEDDED_SUPPORT "Build phApi with embedded target support" OFF)
option(PHAPI_SPEEXWB_REPLACES_AMRWB_HACK "Build phApi with Speex-WB/AMR-WB hack" OFF)
option(PHAPI_SPEEXWB_REPLACES_AMRNB_HACK "Build phApi with Speex-WB/AMR-NB hack" OFF)
option(PHAPI_SPEEXWB_REPLACES_G726WB_HACK "Build phApi with Speex-WB/G726-WB hack" ON)
