env = WengoGetEnvironment()

defines = { 'PHAPI_DLL' : 1 }

libs = [
	'phapi'
]

lib_path = []
include_path = ['../phapi']
headers = []
sources = [
	'miniua.c'
]

lib_flags = []
cc_flags = [
]

if WengoOSMacOSX():
   lib_flags = [
	'-framework CoreAudio',
	'-framework AudioToolbox',
	'-framework AudioUnit',
	'-framework Cocoa',
	'-framework Quicktime',
   ]	

if WengoOSLinux():
   libs += ["z", "owcurl", "portaudio"]

if WengoOSWindows():
    defines['WIN32'] = 1
    env.LinkFlags.removeLinkFlags(env, ['/subsystem:windows'])
    env.WengoAddLinkFlags(['/subsystem:console'])

env.WengoAddCCFlags(cc_flags)
env.WengoAddLinkFlags(lib_flags)
env.WengoAddDefines(defines)
env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoProgram('miniua', sources)
