env = WengoGetEnvironment()

libs = []
lib_path = []
include_path = [
	'.'
]
defines = {}
headers = []
sources = [
	'tinystr.cpp',
	'tinyxml.cpp',
	'tinyxmlerror.cpp',
	'tinyxmlparser.cpp'
]

env.WengoAddIncludePath(include_path)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('tinyxml', sources)
