env = WengoGetEnvironment()

libs = []
lib_path = []
include_path = ['.']
defines = {}
headers = []
sources = [
  'msdirent.c',
]

env.WengoAddIncludePath(include_path)
env.WengoAddDefines(defines)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('msdirent', sources)
