env = WengoGetQt4Environment()

libs = [
	'qt4',
	'owutil',
	'owthread',
]
lib_path = []
include_path = ['include']
headers = [
	'include/qtutil/EventFilter.h',
	'include/qtutil/KeyEventFilter.h',
	'include/qtutil/MouseEventFilter.h',
	'include/qtutil/PaintEventFilter.h',
	'include/qtutil/EnabledChangeEventFilter.h',
	'include/qtutil/PostEvent.h',
	'include/qtutil/WidgetFactory.h',
	'include/qtutil/Object.h',
	'include/qtutil/QObjectThreadSafe.h',
	'include/qtutil/ResizeEventFilter.h',
	'include/qtutil/NonResizeableWidget.h',
	'include/qtutil/StringListConvert.h',
	'include/qtutil/Widget.h',
	'include/qtutil/WengoStyleLabel.h',
	'include/qtutil/ToolTipLineEdit.h',
	'include/qtutil/ClickableLabel.h',
	'include/qtutil/WidgetBackgroundImage.h',
	'include/qtutil/Wizard.h',
	'include/qtutil/QtThreadEvent.h',
	'include/qtutil/ThreadEventFilter.h',
	'include/qtutil/PixmapMerging.h',
	'include/qtutil/SafeConnect.h',
	'include/qtutil/LanguageChangeEventFilter.h',
	'include/qtutil/CloseEventFilter.h',
    'include/qtutil/UpQComboBox.h',
	'include/qtutil/AnimatedButton.h',
	'include/qtutil/DesktopService.h',
	'include/qtutil/UpQComboBox.h',
	'include/qtutil/LinkLabel.h',
	'include/qtutil/ScrollFrame.h',
	'include/qtutil/ThumbnailView.h',
	'include/qtutil/ImageSelector.h',
	'src/QtThumbnailManager.h',
	'src/QtThumbnailDirModel.h',
]

sources = [
	'src/EventFilter.cpp',
	'src/KeyEventFilter.cpp',
	'src/MouseEventFilter.cpp',
	'src/PaintEventFilter.cpp',
	'src/EnabledChangeEventFilter.cpp',
	'src/WidgetFactory.cpp',
	'src/Object.cpp',
	'src/QObjectThreadSafe.cpp',
	'src/ResizeEventFilter.cpp',
	'src/NonResizeableWidget.cpp',
	'src/StringListConvert.cpp',
	'src/Widget.cpp',
	'src/WengoStyleLabel.cpp',
	'src/ToolTipLineEdit.cpp',
	'src/ClickableLabel.cpp',
	'src/WidgetBackgroundImage.cpp',
	'src/Wizard.cpp',
	'src/ThreadEventFilter.cpp',
	'src/PixmapMerging.cpp',
	'src/SafeConnect.cpp',
	'src/LanguageChangeEventFilter.cpp',
	'src/CloseEventFilter.cpp',
    'src/UpQComboBox.cpp',
	'src/AnimatedButton.cpp',
	'src/DesktopService.cpp',
	'src/UpQComboBox.cpp',
	'src/LinkLabel.cpp',
	'src/ScrollFrame.cpp',
	'src/ThumbnailView.cpp',
	'src/ImageSelector.cpp',
	'src/QtThumbnailDirModel.cpp',
	'src/QtThumbnailManager.cpp',

	env.WengoCompileQt4Resource('qtutil.qrc'),
]

if WengoOSMacOSX():
	sources += [ 'src/MacDesktopService.cpp' ]
	headers += [ 'include/qtutil/MacDesktopService.h' ]
	include_path += ['/Developer/Headers/FlatCarbon/' ]

if WengoOSWindows():
	sources += [ 'src/WindowsDesktopService.cpp' ]
	headers += [ 'include/qtutil/WindowsDesktopService.h' ]

forms = [
	'src/Wizard.ui',
	'src/ImageSelector.ui',
]

for form in forms:
	header = env.WengoCompileQt4UiFile(form)
	headers += [ header ]

def moc(env, headers):
	moced = []
	for header in headers:
		moced += [ env.Moc(header) ]
	return moced
moced = moc(env, headers)

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('qtutil', sources + moced, headers)

env.SConscript('tests/SConscript')
