env = WengoGetQt4Environment()

libs = [
	'qt4',
	'owutil'
]
lib_path = []
include_path = ['include']
headers = [
	'include/qtutil/EventFilter.h',
	'include/qtutil/KeyEventFilter.h',
	'include/qtutil/MouseEventFilter.h',
	'include/qtutil/PaintEventFilter.h',
	'include/qtutil/EnabledChangeEventFilter.h',
	'include/qtutil/PostEvent.h',
	'include/qtutil/WidgetFactory.h',
	'include/qtutil/Object.h',
	'include/qtutil/QObjectThreadSafe.h',
	'include/qtutil/ResizeEventFilter.h',
	'include/qtutil/NonResizeableWidget.h',
	'include/qtutil/StringListConvert.h',
	'include/qtutil/Widget.h',
	'include/qtutil/QtWengoStyleLabel.h'
]
sources = [
	'src/EventFilter.cpp',
	'src/KeyEventFilter.cpp',
	'src/MouseEventFilter.cpp',
	'src/PaintEventFilter.cpp',
	'src/EnabledChangeEventFilter.cpp',
	'src/WidgetFactory.cpp',
	'src/Object.cpp',
	'src/QObjectThreadSafe.cpp',
	'src/ResizeEventFilter.cpp',
	'src/NonResizeableWidget.cpp',
	'src/StringListConvert.cpp',
	'src/Widget.cpp',
	'src/QtWengoStyleLabel.cpp'
]

def moc(env, headers):
	moced = []
	for header in headers:
		moced += [ env.Moc(header) ]
	return moced
moced = moc(env, headers)

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('qtutil', sources + moced, headers)
