env = WengoGetQt4Environment()

libs = [
	'qt4',
	'owutil',
	'owthread',
]
lib_path = []
include_path = ['include']
headers = [
	'include/qtutil/EventFilter.h',
	'include/qtutil/KeyEventFilter.h',
	'include/qtutil/MouseEventFilter.h',
	'include/qtutil/PaintEventFilter.h',
	'include/qtutil/EnabledChangeEventFilter.h',
	'include/qtutil/PostEvent.h',
	'include/qtutil/WidgetFactory.h',
	'include/qtutil/Object.h',
	'include/qtutil/QObjectThreadSafe.h',
	'include/qtutil/ResizeEventFilter.h',
	'include/qtutil/NonResizeableWidget.h',
	'include/qtutil/StringListConvert.h',
	'include/qtutil/Widget.h',
	'include/qtutil/WengoStyleLabel.h',
	'include/qtutil/ToolTipLineEdit.h',
	'include/qtutil/ClickableLabel.h',
	'include/qtutil/WidgetBackgroundImage.h',
	'include/qtutil/Wizard.h',
	'include/qtutil/QtThreadEvent.h',
	'include/qtutil/ThreadEventFilter.h',
	'include/qtutil/StatusBarStyle.h',
	'include/qtutil/ToolBarStyle.h',
	'include/qtutil/PixmapMerging.h',
]
sources = [
	'src/EventFilter.cpp',
	'src/KeyEventFilter.cpp',
	'src/MouseEventFilter.cpp',
	'src/PaintEventFilter.cpp',
	'src/EnabledChangeEventFilter.cpp',
	'src/WidgetFactory.cpp',
	'src/Object.cpp',
	'src/QObjectThreadSafe.cpp',
	'src/ResizeEventFilter.cpp',
	'src/NonResizeableWidget.cpp',
	'src/StringListConvert.cpp',
	'src/Widget.cpp',
	'src/WengoStyleLabel.cpp',
	'src/ToolTipLineEdit.cpp',
	'src/ClickableLabel.cpp',
	'src/WidgetBackgroundImage.cpp',
	'src/Wizard.cpp',
	'src/ThreadEventFilter.cpp',
	'src/StatusBarStyle.cpp',
	'src/ToolBarStyle.cpp',
	'src/PixmapMerging.cpp',
]
forms = [
	'src/Wizard.ui',
]

for form in forms:
	header = env.WengoCompileQt4UiFile(form)
	headers += [ header ]

def moc(env, headers):
	moced = []
	for header in headers:
		moced += [ env.Moc(header) ]
	return moced
moced = moc(env, headers)

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('qtutil', sources + moced, headers)
