
#ifndef __LISTENER_IMPL_H__
#define __LISTENER_IMPL_H__

#include "nsISupports.h"
//#include "nsString.h"
//#include "nsCOMPtr.h"
//#include "nsStringAPI.h"

// autogenerated by the idl
#include "IListener.h"

// {7BBEF0D1-10A0-43fd-AB27-EB6893C1F57E}
// uid by Max
#define LISTENER_CID						\
  { 0x7bbef0d1, 0x10a0, 0x43fd,					\
      { 0xab, 0x27, 0xeb, 0x68, 0x93, 0xc1, 0xf5, 0x7e } }

#define LISTENER_CONTRACTID	"@openwengo.com/coiplistener;1"
#define LISTENER_CLASSNAME	"COIP Listener Component"

/* Header file */
class CListener: public IListener
{
public:
  NS_DECL_ISUPPORTS
  NS_DECL_ILISTENER

  CListener();

private:
  ~CListener();

protected:

};

#endif
