
#ifndef __SYSTEMTOOLS_IMPL_H__
#define __SYSTEMTOOLS_IMPL_H__

#include "nsISupports.h"

// autogenerated by the idl
#include "nsISystemTools.h"

// {3B0524D7-844B-44c6-B4D4-86AF213C5338}
// uid by Max
#define SYSTEMTOOLS_CID						\
  { 0x3b0524d7, 0x844b, 0x44c6,					\
    { 0xb4, 0xd4, 0x86, 0xaf, 0x21, 0x3c, 0x53, 0x38 } }

#define SYSTEMTOOLS_CONTRACTID	"@openwengo.com/systemtools;1"
#define SYSTEMTOOLS_CLASSNAME	"OpenWengo System Tools"

// include the file from the extern library
// coming from XPCOM
#include "SystemTools.h"

/* Header file */
class nsSystemTools: public nsISystemTools
{
public:
	NS_DECL_ISUPPORTS
	NS_DECL_NSISYSTEMTOOLS

	nsSystemTools();

private:

	~nsSystemTools();

	SystemTools *_systemTools;

protected:
};

#endif
