env = WengoGetQt4Environment()

link_flags = [
]

libs = [
	'qtutil',
	'qt4',
]

headers = [
]

sources = [
	'desktopservice.cpp',
]

if WengoOSMacOSX():
	frameworks = [ 
		'CoreAudio',
		'AudioToolbox',
		'AudioUnit',
		'CoreServices'
	]

	env.WengoAddFrameworks(frameworks)

env.WengoUseLibraries(libs)
env.WengoAddLinkFlags(link_flags)
env.WengoProgram('desktopservice-tests', sources, headers)

