env = WengoGetEnvironment()

qtwengophone_source_translations = [
	'qtwengophone_fr.ts',
	'qtwengophone_en.ts',
]

if WengoGetConsoleArgument('update-qtwengophone-translations'):
	env.WengoCopyToBuildDir('..\lang\\', 'wengophone\src\presentation\qt\lang')
	env.WengoQtUpdateTranslations(qtwengophone_source_translations)

qtwengophone_translations = [
	env.WengoQtLanguageRelease('qtwengophone_fr.ts', 'qtwengophone_fr.qm'),
	env.WengoQtLanguageRelease('qtwengophone_en.ts', 'qtwengophone_en.qm'),
]

env.WengoAlias('qtwengophone-translations', qtwengophone_translations)
