env = WengoGetEnvironment()

wengophone_source_translations = [
	'wengophone_fr.ts',
	'wengophone_en.ts',
]

if WengoGetConsoleArgument('update-translations'):
	env.WengoCopyToBuildDir('..\lang\\' , 'wengophone\src\presentation\qt\lang')
	env.WengoQtUpdateTranslations(wengophone_source_translations)

wengophone_translations = [
	env.WengoQtLanguageRelease('wengophone_fr.ts', 'wengophone_fr.qm'),
	env.WengoQtLanguageRelease('wengophone_en.ts', 'wengophone_en.qm'),
]

env.WengoAlias('wengophone-translations', wengophone_translations)
