# 
# WengoPhone, a voice over Internet phone
#
# Copyright (C) 2004-2005  Wengo
# Copyright (C) 2005 Mathieu Stute
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

env = WengoEnvironment()
webcam_env = WengoQtEnvironment(env)

webcam_env.WengoUseLibrary("webcam")
webcam_env.WengoUseLibrary("libavcodec")
webcam_env.WengoUseLibrary("systemperf")
#webcam_env.WengoUseLibrary("sdl")

if webcam_env.WengoOsIsWindows():
	webcam_env.WengoLibAddMultiple( [ "strmiids", "comsupp", 'user32', 'OpenGL32', 'gdi32'] )
	webcam_env.WengoLinkFlagsAdd("/subsystem:windows")

sources = [ "webcam_test.cpp", "OpenGlWidget.cpp" ]
webcam_test_prog = webcam_env.WengoProgram("webcam_test", sources)
webcam_env.WengoAlias("webcam_test", webcam_test_prog)

sources = [ "webcam_test_dx_driver.cpp" ]
webcam_test_prog = webcam_env.WengoProgram("webcam_test_dx_driver", sources)
webcam_env.WengoAlias("webcam_test_dx_driver", webcam_test_prog)
