env = WengoGetQt4Environment()

lib_path = []
include_path = []

libs = [
	'qt4',
	'softupdater',
]

headers = []

sources = [
	'main.cpp',
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)

env.WengoProgram('softupdater-test', sources, headers)
