env = WengoGetEnvironment()

libs = [
	'owutil',
	'owserialization',
	'tinyxml',
]
lib_path = []
include_path = ['..']
link_flags = []
headers = []
sources = [
	'src/DateXMLSerializer.cpp',
	'src/TimeXMLSerializer.cpp',
]

env.WengoAddIncludePath(include_path)
env.WengoUseLibraries(libs)
env.WengoAddDoxyfile()

env.WengoStaticLibrary('owserializer', sources)

env.SConscript('tests/SConscript')
